### ISSUE TITLE
Don't choke on missing database.yml

### ISSUE THREAD

**Issue by aflatter** [rom-rb/rom#100]
<a href="https://github.com/solnic"><img src="https://avatars.githubusercontent.com/u/1066?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [solnic](https://github.com/solnic)**
_Friday Jan 02, 2015 at 20:01 GMT_
_Originally opened as https://github.com/rom-rb/rom-rails/issues/10_

----

Setup should be simply skipped with a warning that there's no config file

**Comment by aflatter** [comment]
<a href="https://github.com/aflatter"><img src="https://avatars.githubusercontent.com/u/168?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aflatter](https://github.com/aflatter)**
_Wednesday Jan 07, 2015 at 18:41 GMT_

----

I guess in the preparation phase (before initializers run) we'd just not define a default repository. If initializers don't configure a repository at all, we should skip setup and warn. That way, you don't get a warning if you use neither AR nor rom-sql, but something else. How does that sound?

**Comment by aflatter** [comment]
<a href="https://github.com/solnic"><img src="https://avatars.githubusercontent.com/u/1066?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [solnic](https://github.com/solnic)**
_Wednesday Jan 07, 2015 at 20:14 GMT_

----

Yes that sounds correct

**Comment by solnic** [comment]
@aflatter IIRC this is fixed, right?
