### ISSUE TITLE
Extend Command API with error/success handling

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#104]
Idea for an api:

``` ruby
result = rom.command(:users).try { create(name: 'Jane'  }

result
  .on_error { |err|
    # handle err
  }
  .on_success { |user|
    # do your stuff
  }
```

**Comment by aflatter** [comment]
I'd prefer the naming to not be callback-oriented. You try to run a command and you get back a result which is simply a value.

**Comment by aflatter** [comment]
```ruby
result = rom.command(:users).try { create(name: 'Jane') }

result.or_else { |error| ... }
      .and_then { |result| ... }

result.value # fails if command was not succesful
```

**Comment by aflatter** [comment]
Maybe Rust's `std::result` can serve as inspiration here: http://doc.rust-lang.org/0.11.0/std/result/type.Result.html

**Comment by solnic** [comment]
Yeah I like that. It's closer to `try` that we already have.

**Comment by elskwid** [comment]
I like the Rust `std::result` more than I like `on_error`, `or_else`, `and_then`. Agreed that `on_error` feels more like standard callbacks, and `or_`/ `and_` seems to denote an order of operation as opposed to simple error handling.

In the interest of listing options: Perhaps some of the Promise implementations can serve as inspiration:

https://github.com/petkaantonov/bluebird
https://github.com/tildeio/rsvp.js

```ruby
result = rom.command(:users).try { create(name: 'Jane'  }

result
  .then { |user|
    # user stuff
  }
  .then { |user|
    # other user stuff
  }
  .catch { |err|
    # handle error
  }
```

**Comment by solnic** [comment]
Damn, this is nice too. Hmmmm

**Comment by snusnu** [comment]
what is the motivation behind adding additional api to the result object? imo, as long as the result object encapsulates associated context (i.e. the value in case of success or an error object/symbol in case of failure), rom users are free to handle/integrate their error handling how they like

**Comment by solnic** [comment]
To establish conventional way of dealing with result objects. Notice that it wouldn't enforce the usage. You can still handle result as you like. This applies to commands themselves. You can access them directly and call them and catch errors yourself and so on.

**Comment by snusnu** [comment]
fair enough, i just wanted to question *adding* api that's not strictly necessary. fwiw, i think that if such api is added, it should help with dispatch, i.e. something like the suggested `#then` which yields the result value "unconditionally" wouldn't really help, would it? If you dispatch on success vs. error state tho, you save yourself a conditional in client code.

**Comment by solnic** [comment]
I don't think it'd work like you think - this is building an object that would execute individual blocks only for specific responses when you 'unwrap' a value from it. So `.then` would only be executed when response is a success, for an error response it would be a no-op.

**Comment by elskwid** [comment]
Another take on the topic mentioned in chat: https://github.com/snusnu/orc

**Comment by solnic** [comment]
IIRC we decided to go with something similar to Rust's Result - I really like it, looks like a great source of inspiration. Anybody would like to tackle this? Shall we have that as a last-minute 0.6.0 addition? :)

**Comment by solnic** [comment]
OK after all those months of ROM usage I realized we don't need to integrate with any external lib for command results. It's OK to add `success?` and `failure?` methods as per #266 request and do whatever you want using whatever control-flow lib you like or plain ruby with conditional statements.

Having said that, I'm going to close this issue. Please tell me if you you disagree.
