### ISSUE TITLE
Improve in-memory adapter and make it 1st-class citizen in public API

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#105]
In-memory adapter has a great potential to be used for combining data from multiple repositories. There are a couple of things that should be done to make it better:
- [ ] extract read-only interfaces into a separate mixin
- [ ] extract insert/update/delete into a separate mixin
- [ ] make it possible to configure the adapter in read-only mode
- [ ] make it possible to configure the adapter in full read/write mode
- [ ] make it possible to use base in-memory adapter logic in other adapters (like csv or yaml) - maybe just extract reading-related ops (join, project etc.) into a mixin so that other adapters can simply include it rather than inheriting from some "base" class

**Comment by solnic** [comment]
It was suggested that a virtual relation (which combines other relations and is not derived from a single base one) doesn't need a repository, which is absolutely true, so let's keep that in mind.

**Comment by maetl** [comment]
One API quirk I’ve noticed from usage of this is the following tends to pop up in a few places:

```ruby
class NamedCollection < ROM::Relation[:memory]
  forward(:reverse)

  def by_recent
    order(:date_thing).reverse
  end
```
