### ISSUE TITLE
Support configuration of repositories via `config/rom.yml`

### ISSUE THREAD

**Issue by aflatter** [rom-rb/rom#108]
There's a helper in Rails for loading configuration that already respects environments: [Rails::Application#config_for](http://api.rubyonrails.org/classes/Rails/Application.html#method-i-config_for).

I think we should use this. Thoughts?

**Comment by solnic** [comment]
In addition to supporting database.yml, right?

**Comment by aflatter** [comment]
Yes. As I see it, `config/rom.yml` would be optional. You'd be free to define your repositories in an initializer if you like that better. `config/rom.yml` would have higher priority than deriving the default repo from ActiveRecord though.

**Comment by solnic** [comment]
This sounds good

**Comment by aflatter** [comment]
This should be quite easy to implement, making it a good candidate for `help-wanted`!

**Comment by kchien** [comment]
@aflatter I started looking into this, but it appears that to use `Rails::Application#config_for`, you need an instance of the app.  Will some of the code that was removed in rom-rb/rom-rails@d00c4f4e0defd15fe2859a4394cfa7ce9e2c2389 have to be brought back?  Is there another way to pass the app to `ActiveRecord::Configuration`?

**Comment by aflatter** [comment]
@kchien I don't think you need touch `ActiveRecord::Configuration`. Instead, you can check hook into the initizliation process [here](https://github.com/rom-rb/rom-rails/blob/master/lib/rom/rails/railtie.rb#L32) and construct a `ROM::Rails::Configuration` by reading from the YML file if it exists.

`ActiveRecord::Configuration` is just for reading the default connection hash directly from ActiveRecord and converting it to Sequel style. It shouldn't need to know anything about ROM.

Does that help? :+1:

**Comment by solnic** [comment]
Any ideas on the structure of this file? Something like:

``` yaml
repositories:
  default:
    adapter: postgres
    database: rom_test
  other:
    adapter: yaml
    database: locales
```

??

**Comment by solnic** [comment]
OK this ain't gonna happen. You can easily configure ROM using its interface, no need for extra complexity that comes with parsing some yaml files.

I feel very strong about this so I'm going to close this issue. If somebody can come up with good arguments why this is a good idea, please comment and we can discuss.
