### ISSUE TITLE
Registry::ElementNotFoundError not raised anymore if relation does not exist

### ISSUE THREAD

**Issue by aflatter** [rom-rb/rom#109]
`rom-rails` is now failing on Travis, e.g. [here](https://travis-ci.org/rom-rb/rom-rails/jobs/46840818), because the database backing relations does not exist yet when running the `app:db:schema:load` task. Previously this problem was countered by catch `Registry::ElementNotFoundError`.

**Comment by aflatter** [comment]
And by "now", I mean after #106 was merged ;-)

**Comment by solnic** [comment]
I'm working on it but it's tricky. Now we end up with Sequel error because we try to access a dataset immediately. I have some ideas how to fix it. I will send a PR because I don't feel strong about the solution :/

**Comment by solnic** [comment]
This was fixed via [this](https://github.com/aflatter/rom-sql/commit/0f188669285d505a1f102fb7b3ff23e756b0b76c) commit in rom-sql
