### ISSUE TITLE
Remove Env#method_missing and Env#

### ISSUE THREAD

**Issue by aflatter** [rom-rb/rom#111]
- `Env#method_missing` currently lets us access repositories directly using the repository name, but it also provokes naming collisions with all other methods defined in `Env`.
- `env[repository_name]` does not have any collision issues, but it's also not used too much.

Let's remove these things as discussed in favor of `env.repositories` before the API becomes too stable.

**Comment by solnic** [comment]
Just to add more context - this was introduced to make it easier to access native interfaces exposed by adapters. It's been a workaround though as adapters should provide common interfaces to relation objects so accessing repositories is not a common thing to do
