### ISSUE TITLE
Introduce migration interface

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#113]
Currently to use Sequel's migration DSL you need to access sequel connection object directly like `rom.repo_name.adapter.connection.create_table ...`. We need to come up with some custom interface and hide implementation details related to sequel.

Maybe something like:

``` ruby
rom.repo_name.create_table { } # simply delegates to connection under-the-hood
```

**Comment by kwando** [comment]
I would like to see something high level framework/API for migrations, where it would be possible to migrate multiple repositories (with different adapters) in the same migration script. Ofc the details would be adapter-specific.

**Comment by solnic** [comment]
It would require a huge infrastructure, we could consider doing that at some point, right now it's not really feasible in my opinion. I would also argue if it should be part of ROM.

**Comment by kwando** [comment]
yeah, it is not a small project... just dreaming =)

**Comment by solnic** [comment]
There are advanced projects for migrations out there :)

**Comment by solnic** [comment]
Closing this as we have a migration interface in rom-sql now added in [this](https://github.com/rom-rb/rom-sql/commit/6efcaff03b439cef07a4c2ccf9445a73f09084e9) commit
