### ISSUE TITLE
Make it possible to cherry-pick a specific mapper

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#122]
Basically making this possible:

``` ruby
 # this means there's no need to define ":de" relation within base translations one
rom.read(:translations, mapper: :de).to_a
```

**Comment by solnic** [comment]
@aflatter after our recent discussion I believe I should revert it to the original idea of `rom.read(:base_rel_name, mapper: :some_mapper)`. OK?

**Comment by aflatter** [comment]
@solnic ack.

**Comment by solnic** [comment]
@aflatter one more thing - we talked about an alternative interface where you can use a block where you put together a relation and then tell which mapper should load it, IIRC something like:

``` ruby
rom.map(:users, :mapper_name) { active.admins.by_id(1) }.one!
```

Right?

**Comment by aflatter** [comment]
I think our ideas were more like this:

```ruby
# Option 1
rom.read(:mapper_name) { users.active.admins.by_id(1) }.one!
# Option 2
rom.read { users.active.admins.by_id(1) }.map(:mapper_name).one!
```

Note that `users` and the rest of the relation are close together, whereas in your example it's somewhat disconnected. Not sure why the method is called `map` in your example, but I guess it has something to do with your concern about encapsulating data access.

**Comment by solnic** [comment]
Ah yeah that's better. So I guess for `map` to work we'd do something like `if block_given? then super else mappers[mapper_name].process(relation).to_a } end`. That block would be evaluated on some object that has access to relations (we could build it during setup to avoid method_missing). Hmmm

**Comment by solnic** [comment]
@aflatter I'd like to remove instance_exec and yield a relation to the block and then close this issue, so:

``` ruby
rom.read(:users) { |users| users.by_name('Jade') }.map(:foobar)
```

lemme know if that works for you, if not let's talk this through :) I'd like to close this chapter for 0.6.0

**Comment by aflatter** [comment]
It's a bit longer, but easy to understand. :+1:

**Comment by solnic** [comment]
@aflatter we could do the trick with arity :)
