### ISSUE TITLE
Improved command API

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#129]
### Intro

Command API is the latest addition in ROM and is still in experimentation phase receiving a lot of feedback from users and contributors. The goal of this "issue" is to finalize that API, make it easy to understand and keep its extensibility which is already leveraged by rom-sql.

There are a couple of characteristics of the command api which make it potentially hard to understand for people who are familiar (and used to) ActiveRecord and other ORMs with interfaces inspired by AR:

* commands operate on relations, not individual "objects" - when executing a command you always provide the relation, you can restrict it to contain only a single tuple, but it always results in executing some operation *on a relation*
* commands are simple objects - when you register a command under a specific name you have access to this object, you can create new instances of those command objects by providing other relation identifiers and optional args. ie: `rom.commands[:users].update.new(:by_id, 1).call(name: 'Foo')` returns a new "update" command with `rom.relations.users.by_id(1)` set as its relation, then `.call` executes the command. This is what happens when you use `rom.command(:users).try { update(:by_id, 1).set(name: 'Foo')`, it's just a higher-level DSL to access commands
* commands are meant to be functional and composable - a command object doesn't execute any db operation when you create it, instead it carries a context in which something will be executed when you `.call` it. It also doesn't mutate the relation, it uses an adapter-specific interface to make changes in the db but objects that are passed to a command don't get mutated
* commands encapsulate input processing and validation when it's configured via `input` and `validator` macros - both input processing and validation may raise an error which is handled within `.try`, by default those are no-ops so you don't have to define them

### Extension for associations in SQL

rom-sql can extend command API with features that make it easier to work with associations and FKs.

Here's what is considered:

``` ruby
users = rom.command(:users)
tasks = rom.command(:tasks)

user_attrs = { name: 'Jane' }
task_attrs = { title: 'Task One' }

# here's what is currently possible with an explicit approach
users.try {
  create(user_attrs)
} >-> user {
  tasks.try { create(task_attrs.merge(user_id: user[:id])
}

# this could be collapsed to:

# option 1
users.try { create(user_attrs) } >-> user { tasks.associate(user).create(task_attrs) }

# option 2
users.try { create(user_attrs).associate(tasks, task_attrs) }

# option 3 with nested params (probably built on top of something lower-level)
users.try { create(name: 'Jane', task: { title: 'Task One' }) }

# option 4
# ????
```

**Comment by aflatter** [comment]
```ruby
rom.try { users.create(user_attrs) }.and_then { |user| tasks.create(task_attrs.merge(user_id: user[:id])) }
```

**Comment by solnic** [comment]
How about this:

``` ruby

# this would build a composite command where tasks.create would know it should
# associate task with a user by setting its FK

# the try block gets back a command, calls it and rescues from any potential errors
# and returns Result object

rom.commands.try {
  users.create[name: 'Jane'] >> tasks.create[title: 'Jane']
}

# for better readability in sql world we could have it like that:

rom.commands.try {
  users.create[name: 'Jane'].associate(tasks.create[title: 'Jane'])
}
```

Notice the `[]` that would be needed to auto-curry input and postpone execution, if we wanted to use `()` we'd have to put something in front of it...which is exactly why I added `Evaluator` but now I'm thinking it's an unneeded abstraction...with this approach we explicitly access commands removing the need of having something extra on top of it. For me it'd be a win.

**Comment by solnic** [comment]
oh and here's an example of update and delete with this style:

``` ruby
rom.commands.try {
  users.by_id(1).set(name: 'Foo')
}

rom.commands.try {
  users.by_id(1).delete
}
```

**Comment by solnic** [comment]
OK so `Env#try` feels wrong because you need to inject entire ROM env into objects that use commands, meh. So I will move it to command registry so that you can only inject command registries:

``` ruby
users = rom.commands.users
tasks = rom.commands.tasks

users.try { users.create[name: 'Jane'] >> tasks.create[title: 'Task One'] }
```

Makes sense?

**Comment by solnic** [comment]
I made a bunch of improvements in the composable-commands branch which is now merged into master, the API is way simpler now and allows explicitly calling command objects without the intermediate evaluator object. You can also simply refer to a specific relation on the command object (which transparently forwards to relation and returns a new command for a specific relation).

It's a really nice change IMO based on the feedback I've gathered so far. So, eventually it looks like this:

``` ruby
users = rom.commands.users
tasks = rom.commands.tasks

create_user = users.create
create_task = tasks.create

# using try with a command object that you just call
users.try { create_user.call(name: 'Jane') }
tasks.try { create_task.call(title: 'Do something') }

# you can now compose two commands and call it eventually
# return value from the first is passed into the next

command = create_user.curry(name: 'Jane') >> create_task.curry(title: 'Do something')
command.call # now created user is passed to create_task#execute

# update and delete can access relations using a method call that looks like accessing a relation
# following examples assume you have `by_id` and `by_name` relations defined on users base relation
update_users = users.update
delete_users = users.delete

update_users.by_id(1).set(name: 'Jade') # notice that "set" is just an alias for "call"

delete_users.call # deletes all the users
delete_users.by_name('Jade').call # delete users with name == 'Jade'
```
