### ISSUE TITLE
Integrate with sequel migrations

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#130]
Currently rom-sql provides no integration with any migration mechanism, hence you need to use either AR's migrations (which works just fine but is obviously not a final solution) or plug in sequel migrations, it's probably a good idea to extract sequel migrations part from [sequel-rails](https://github.com/TalentBox/sequel-rails) and integrate it with rom-sql.

**Comment by gotar** [comment]
Will take care of it, or try ;] you can check progress: https://github.com/gotar/rom-sql/tree/%23130-migrations

**Comment by solnic** [comment]
@gotar w00t!

**Comment by gotar** [comment]
i think we can close this ticket @solnic

**Comment by solnic** [comment]
Right!!
