### ISSUE TITLE
Question: Overriding `#to_h` of command input class

### ISSUE THREAD

**Issue by mcls** [rom-rb/rom#134]
In my app I have a form which only takes a YouTube url as input and transform that into a `Video` model. That transformation happens in the input object, which required me to override the `#to_h` method. 

Is that the correct place to handle this? I kind of like this approach, but felt a bit weird overriding `#to_h`.

```ruby
class Video
  include Virtus.value_object(coerce: false)

  values do
    attribute :id, Integer
    attribute :youtube_id, String
    attribute :title, String
    attribute :username, String
    attribute :published_at, DateTime
  end
end



class Video::Params
    attribute :url, String

    def youtube_id
      matches = YOUTUBE_REGEXP.match(url)
      matches ? matches[:yid] : ""
    end

    def to_h
      to_video_model.attributes.except(:id)
    end

    private

    # @return [Video]
    def to_video_model
      # Calls YouTube API and uses response to initialize Video model
      Video::FromYoutube.call(youtube_id)
    end
  end
end



ROM.commands(:videos) do
  define(:create_from_youtube, type: :create) do
    input Video::Params
    validator Video::Validator
    result :one
  end
end
```

Also had a question about this code: 
https://github.com/rom-rb/rom/blob/f024a9bc2c088c02105825a4887631649ff63ac2/lib/rom/memory/commands.rb#L8-L10

Is the `.[]` a `Virtus` thing? Or some ruby-ism I don't know about?

**Comment by solnic** [comment]
Params are designed to handle input sent from "the outside", if you need to build attributes based on params you need a separate object to do so (like your '`Video::FromYoutube`). I see that in your case you construct attributes based on a url (that's your input) and then you pass in those attribute to the command. I would probably model it in a way where there's a form object with params having a url, validate that url and use it to build attributes for the command (there's no need to specify special command input class in this case IMO).

Something like that:

``` ruby
ROM.commands(:videos) do
  define(:create_from_youtube, type: :create) do
    # if you don't trust your FromYoutube you can specify params and validator handlers
    input Video::YoutubeParams # params that are constructed by FromYoutube
    validator Video::YoutParamsValidator # dedicated validator for those params

    result :one
  end
end

# then the VideoForm models the actual form which (as I understand it) sends a URL, which should be
# valid so that FromYoutube can work with it
class VideoForm < ROM::Model::Form
  inject_commands_for :videos

  input do
    set_model_name 'Video'

    attribute :url, String
  end

   validations do
     validate :url, presence: true # probably more is needed
  end

  def commit!
    attributes = FromYoutube.call(youtube_id)

    videos.try { |command| command.create_from_youtube(attributes) }
  end
end
```

This assumes `FromYoutube.call` always returns a valid set of attributes and crashes with an exception that is handled outside of the scope of the form (some http errors and such). You could of course handle it in the form but there's no conventional interface for such errors (not yet at least).

As a general design principle Form objects must model the actual web forms. I's only responsibility is to define structure of input, validation rules and send it to the command. If actual attributes are different from the original input (as in this case) then it's totally fine to map them to something else using an external dependency (like FromYoutube) and send to command, notice that command's input/validators would be different from the form's input/validation.

The `.[]` is not virtus', it is ROM's `Model::Params` interface as that's the interface commands depend on.

I think this use-case is a beautiful example how ROM pushes towards separation of concerns. It is probably harder to understand when we're so used to a single object (AR) that would handle ~90% of what's happening there. I believe it is only a matter of time to get used to this approach. We can come up with many conventional interfaces working on a high-level that are using small lower-level components (like Form already does) but once things get complicated you can easily break them down, re-use them in many places, test them separately etc. For me that's a huge benefit.

I already used Form in my app and it feels as simple as when using AR, so I think we're getting there with the ease of usage too.

**Comment by mcls** [comment]
Thanks for explaining that :)

If I understand it correctly there will be two validation steps:

1. Validate the form's inputs (`url`)

2. Validate the params passed to the command (the data returned by `FromYoutube`)

This what I now have in my `VideoForm#commit!`:

```ruby
  def commit!
    videos.try { |command|
      # Run form validations, `#try` will catch the validation error
      input = self.class.params[params]
      self.class.validator.call(input)

      model = Video::FromYoutube.call(input.youtube_id)
      attrs = model.attributes.except(:id)
      command.create(attrs)
    }
  end
```

**Comment by mcls** [comment]
I have to call the validator inside `commit!` now, 
because it's different from the one defined on the command.

**Comment by solnic** [comment]
Yeah, it kinda sucks I have to admit. Form is built with the assumption that command will use input and validator handlers. Hmmm. I guess that's why I was reluctant to introducing form objects in general haha, it's assuming a lot. I need more time to think how to extend the interface so that we can model your use case better.

This is actually a pretty common thing to do - receive some input and *map it* to something that will be persisted. This means you need 2 validators, one for received input to make sure its structure matches requirements and another one for the actual attributes that will be send to the db.

I've got a hunch that we could have an abstract object for handling a generic scenario `raw input => mapped input => validation => custom action` and derive `Form` from it. This way you could derive your own class from it too and simply use form instance inside of it as an external dependency. Something like that maybe:

``` ruby
class CreateVideo < ROM::Model::SomeFancyAbstractInputValidationHandlerThingie
  inject_commands_for :videos

  uses :video_form

  def commit!
    videos.try { |command|
      command.create(video_form.attributes)
    } 
  end

class VideoForm < ROM::Model::Form
   # all the stuff

  def attributes
    validate!(input)
  end

  private

  def input
    self.class.params[params]
  end

  def validate!(input)
    self.class.validator.call(input)
  end
end
```

**Comment by solnic** [comment]
Ah there's one detail I should mention: those fancy objects should also register commands so that you don't have to do it *unless* you don't want them to in cases where you re-use "raw" commands in other places. This will be added soon and should simplify the setup a lot.

**Comment by solnic** [comment]
I'll be making some improvements in Form interface so I'll try to address this one too and make it better for you :)

**Comment by solnic** [comment]
This is resolved as now you need to pass in already coerced input using `Form#attributes` interface to the command. This means you control when and how input is processed.
