### ISSUE TITLE
Add ability to register a relation under a different name than base_name

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#137]
Right now `base_name` is used as the name under which a relation will be registered in the env, this makes it not possible to register multiple relations pointing to the same `base_name` (in sql words, a database table). We could easily make it possible to register multiple relations pointing to the same `base_name` by using a new interface ie `register_as` (which is already used for commands btw).

So, it could look like that:

``` ruby
module Relations
  class Users < ROM::Relation[:sql]
    base_name :users
  end
end

module Admin
  module Relations
    class Users < ROM::Relation[:sql]
      base_name :users
      register_as :admin_users
    end
  end
end
```

**Comment by aflatter** [comment]
@solnic probably a good time to rename base_name to dataset, wdyt?

**Comment by solnic** [comment]
@aflatter dammit I forgot about this :D yeah `dataset` is much better and describes what it actually is...we should rename it
