### ISSUE TITLE
rom-sql not coexisting with ActiveRecord

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#143]
The new rake tasks, `db:migrate` and company, do not cooperatively coexist with ActiveRecord.

```
flip@jakarta:~/src/get_ready_server (master) $ rake db:migrate
rake aborted!
Don't know how to build task 'load_setup'

Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
That from a Rails 4.2 project with HEAD rom-*.

I suspect it would be nicer to claim a different namespace, or at least to not automatically lay claim to the `db:` namespace already homesteaded by ActiveRecord without intentional user intervention.

**Comment by cflipse** [comment]
(also, I suspect that there's something off with a rake load path, that it's not finding the task it's depending on ...)

**Comment by solnic** [comment]
We shouldn't include migration tasks by default. I'll fix that

**Comment by solnic** [comment]
We're not going to enable migrations in Rails by default, this is a highly experimental and fresh feature so needs more work.
