### ISSUE TITLE
Update generator templates to produce classes rather than DSL incantations

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#148]

**Comment by cflipse** [comment]
I'll pick this one up.

Adjusting the Mapper and Relation generators to:
 * Produce the class version
 * use autoload-safe file names
 * accept an optional adapter argument

And add a generator for Forms
 * optional adapter argument to generator
 * generate an integration spec/test for the form

**Comment by solnic** [comment]
Sounds like a good plan :)

**Comment by cflipse** [comment]
Anything left on this?  Between rom-rails#30 and rom-rails#25  I think it's been covered?

**Comment by solnic** [comment]
True! Closing, thanks :heart:
