### ISSUE TITLE
Add an interface to specify "base" dataset

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#154]
Right now rom-sql is completely bare-bone with no conventions wrt default dataset. It might be worth considering a way to specify the base dataset that will be injected so that it will always be used as "the starting point". Don't confuse this with "default scope" in AR - this is an anti-pattern. We're talking about some absolutely basic convention, ie always select all attributes and sort by PK. rom-sql could set it up for you automatically and give you a way to override it too.

Here are some API sketches:

``` ruby
module MyApp
  module Relations
    class Users < ROM::Relation[:sql]
      dataset(:users) do
        select(:id, :name, :email).order(:id)
      end

      def by_name(name)
        # and now this is based on the one we defined above
        where(name: name)
      end
    end
  end
end
```

**Comment by kwando** [comment]
Oh, this would be awesome =)

I usually define  a private ```base``` method that all other methods is using.

```ruby
class UsersRelation < ROM::Relation[:sql]
  dataset(:users)
  
  def active
    base.where(active: :true)
  end

  private
  def base
    select(:id, :username, :name).where(deleted: false)
  end
end
```

Having something like you suggesting by default in ROM would be nice option.
