### ISSUE TITLE
Hide inflections behind an internal interface

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#156]
Currently we have a hard dependency on `Inflecto` gem. ROM uses inflections in a couple of places and it would be nice to have internal interface with pluggable backends. Why? Because we could drop hard dependency on `Inflecto` and use a simple detection mechanism to see if there's any inflection backend available (in 90% ActiveSupport should be there heh) and just use that one. We could default to `Inflecto` when there's no AS.

**Comment by mjtko** [comment]
I've had a go at this in #158 -- I'll look at making the couple of required changes to `rom-sql` after the result of any discussion/iteration on the PR.
