### ISSUE TITLE
Postgresql adaptor naming issue in rom-rails.

### ISSUE THREAD

**Issue by cameron-martin** [rom-rb/rom#161]
In rails' `database.yml`, the postgresql adaptor is named 'postgresql'. However, in ROM it is called 'postgres'.

This means ROM tries to look up `Adapter['postgresql']` in [`ROM::Config`][1], which returns nil and eventually raises an error (on a side-note, it might be better to raise an error instead of returning nil).

This is relevant to the the latest releases (rom 0.5.0 and rom-rails 0.2.1), although it might not be relevant to master since it looks like lots of things have changed.

[1]: https://github.com/rom-rb/rom/blob/v0.5.0/lib/rom/config.rb#L39

**Comment by solnic** [comment]
Thanks for the report - that's fixed on master already
