### ISSUE TITLE
ROM::Commands::Update[:sql]: change(...).to(...) feels inconsistent

### ISSUE THREAD

**Issue by aflatter** [rom-rb/rom#171]
The type of input is configurable by the user, but the type of `original` is hard-coded to be a Hash.

```ruby
class UpdateUser < ROM::Commands[:sql]
  relation :users
  register_as :update
  result :one
  input User
end

original_record = rom.relation(:users).by_id(user_id).as(:user).one!
updated_record = User.new(original_record.attributes.merge(...))
rom.commands.users.update.by_id(user_id).from(original_record).to(updated_record)
# => ROM::InvalidOptionValueError: :original:#<User ...> has incorrect type
```

**Comment by solnic** [comment]
`input` is not for setting domain object models, it's for setting input sanitizer/coercer objects. Commands don't persist "domain objects", they persist data, we're dealing with hashes here exclusively (aka tuples). `from/to` works with hashes, the fact you provide `input User` doesn't mean the command persists a user. It just happens that your class responds to the expected interface (`User[]` and `User#to_h`).

Makes sense?
