### ISSUE TITLE
Uncoercable attributes should not make a form explode

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#180]
In rom-rails, if a form has an integer attribute:

```
class InputForm < ROM::Model::Form
  #...
  input do
    attribute :total, Integer
  end
  # ...
end
```

Assigning an uncoercable value to the attribute  `InputForm.build(total: "two hundred")` will raise an error.  Validations never have a chance to filter and handle this cleanly.  This is undesirable behavior for user facing input.

**Comment by solnic** [comment]
Yeah, I had second thoughts about this myself. We added strict mode by default but it's too aggressive. This is that moment where coercion and validation are really close to each other.

I think you're right - we should turn strict mode off.

**Comment by cflipse** [comment]
fixed in https://github.com/rom-rb/rom-rails/commit/6dd06dc4b280e991c27e1f152335bef6f0d74b7c
