### ISSUE TITLE
Create forms should populate ID

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#181]
after a create form successfully adds a new record, it should populate it's ID field, so that it's usuable in a normal rails controller flow:

```
  form = NewDataForm.build(data_params)

  form.save
  if form.success?
    redirect_to data_path(form)
  else
    render :new, form: form
  end
end
```

**Comment by cflipse** [comment]
presently, I have to dig in for `form.result.value[:id]` to get the show-page redirect that's standard rails controller flow.

**Comment by solnic** [comment]
Actually I think the proper way of doing this is unwrapping the result and using whatever the command returned. We can wrap it up as an object too (this is a missing interface in Form though).

So, something like this would be much nicer:

``` ruby
form = NewDataForm.build(data_params).save

if form.success?
  data_object = form.something_that_returns_the_created_data_object
  redirect_to data_path(object)
else
  render :new, form: form
end
```

...or we could make sure that `to_key` works with a saved form but that's even more mutability in the form object so meeeh.

**Comment by cflipse** [comment]
This looks like it'll blend in _really_ well with #185, once that's in place.

Although I think getting something in place for a 0.3.1 release might still be a good idea, even if it gets updated once rom-0.7.0 goes out.

**Comment by solnic** [comment]
Yep we should push 0.3.1 with those changes merged

**Comment by solnic** [comment]
with #187 merged in we could extend form dsl to support something like that:

```ruby
class CreateUserForm < ROM::Form
  # this would make Form generate a command registry tailored to return entities using :entity mapper
  commands users: :create, as: :entity

  # rest of the stuff
end
```

**Comment by cflipse** [comment]
Yup.  I'll work on wiring that up.

Saw on gittr that you're hoping for a 0.6.1 release sometime this week?

**Comment by solnic** [comment]
@cflipse yes, wrap things up before Thursday and release on Friday

**Comment by cflipse** [comment]
work in progress:  https://github.com/cflipse/rom-rails/tree/result-data-object

In some sense, this feels a bit clunky to me, acutally poking through it.  The suggested API breaks, so I'm starting from a simpler point, and once the basics are down, I can try and shift up to it.  But in looking at it, I'm thinking it might be simpler and more consistent to do something more like:

```ruby
  result = form.save
  object = result.as(:entity)
```

but that requires the result to know about the relation, and it's mapping, and that might be pushing information too far down.

I'm pausing here because it's late and I'm tired; I won't likely get a chance to poke at this again until Thursday, late ... more likely Friday evening.

**Comment by solnic** [comment]
yep makes sense to start as simple as possible :)

**Comment by muescha** [comment]
Question: is `:entity` here a magic static keyword or an entity defined before?

**Comment by cflipse** [comment]
it's the registered name of a mapper.
