### ISSUE TITLE
Support returning entities from commands

### ISSUE THREAD

**Issue by AMHOL** [rom-rb/rom#185]
Currently when you call a command, such as create:

```ruby
ROM.command(:users).create.call(name: 'Test', email: 'test@test.com')
```

The return value is a hash, in most cases it would be useful to return an entity, or collection of entities, this should be relatively simple to implement, suggested API for configuration is:

```ruby
class CreateUser < ROM::Commands::Create[:memory]
  register_as :create
  relation :users
  result :one, as: :entity # The as: :entity option here
end
```

**Comment by AMHOL** [comment]
Wondering about Virtus style syntax for this, i.e.

```ruby
class CreateUser < ROM::Commands::Create[:memory]
  register_as :create
  relation :users
  result Array[User]
end
class CreateUser < ROM::Commands::Create[:memory]
  register_as :create
  relation :users
  result User
end
```

**Comment by solnic** [comment]
no, sorry this can't be done like that - first of all it requires model constants to be defined when commands are loaded, secondly it makes command now how to instantiate objects (which is not their responsibility), thirdly - I *really don't like that syntax anymore*, it can't be used consistently and requires more complexity, it's going away in virtus 2.0.

**Comment by AMHOL** [comment]
Yeah, thought about it when I went to bed last night, realise why you mentioned some kind of DI container as this method relies on constructor mass-assignment.

**Comment by solnic** [comment]
This is done in #187 - pls take a look, I'd like to merge it in :)
