### ISSUE TITLE
ROM does not rescue from Sequel::DatabaseError

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#191]
Reproduction: insert a value to non existent column with rom-sql

**Comment by gotar** [comment]
rom `try` do not catch no rom errors

**Comment by kwando** [comment]
I know, but the error that is raised is a ```ROM::SQL::ConstraintError``` which inherits ```ROM::CommandError```.
The problem with the form code is that the form expects the error to be a ValidationError (which also is kind_of?(ROM::CommandError).

**Comment by solnic** [comment]
So this is a rom-rails bug I suppose.

**Comment by solnic** [comment]
So here's a mystery - it works in tests, but not in console, I'm clueless.

**Comment by cflipse** [comment]
Do the changes in rom-rb/rom-rails#35 address this?

**Comment by solnic** [comment]
We discussed this with @cflipse and agreed that constraint errors and db errors should be re-raised and should be handle by application's code. See recent changes in rom-sql. Closing this one.
