### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#192]
Core components should be extendible through plugins. We already have a pagination plugin in rom-sql and it would be great to generalize the plugin infrastructure so that it's easy to extend ROM.

Here's an API idea:

``` ruby
# it should be possible to register plugins
ROM.plugins do
  # global
  register :publisher, ROM::Plugin::Publisher, type: :command

  # adapter-specific
  adapter :sql do
    register :pagination, ROM::SQL::Plugin::Pagination, type: :relation
  end
end

# then plugins become available
class CreateUser < ROM::Commands::Create[:sql]
  use :publisher
end

class Users < ROM::Relation[:sql]
  use :pagination
end
```

**Comment by cflipse** [comment]
starting some work on this.  You can look over my shoulder at https://github.com/rom-rb/rom/pull/195
