### ISSUE TITLE
Map attributes to array

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#199]
Something to map
```javascript
{
  "tag1": "hello",
  "tag2": "world"
}
````
to
````javascript
{
  tags: ['hello', 'world']
}
````

**Comment by solnic** [comment]
Do you have a use-case like that? I must say I've never seen such a structure.

**Comment by c0** [comment]
My personal use-case:

I'm creating an aggregate object. It's one tuple b/c it's a join of 3 postgres tables (using `rom-sql`'s `association_left_join`). Each relation/table has an array of `amenities`. The aggregate needs to combine the three arrays into one.

One simple way may be to provide multiple keys in the `from:`. For example —

```ruby
attribute :d, from: [:a, :b, :c] do |a, b, c|
  a + b + c
end
```

**Comment by nepalez** [comment]
I like this syntax. But there is some edge cases

1) What would be the proper behaviour by default without a block:

`attribute :d, from: [:a, :b, :c]`

With the data: `{ a: 1, b: 2, c: [3] }`

Should it be: `{ d: [1, 2, 3] }` or `{ d: [1, 2, [3]] }`?

2) How this syntax should be expanded to `unwrap`, `ungroup`, `unfold`:

The trick is the syntax becomes `ungroup f: [:a, :b], from: [:c, :d]`.

And now the data: `[{ a: [{ c: 1, d: 2, e: 3 }], b: [{ c: 4, d: 5, e: 6 }] }]`

How to process this at all (notice `:e` should be left grouped)?

3) following the business case, don't we need to support some sort of uniqueness. When there is one source array we can expect the data are prepared as either unique or not, and we should't change this at the mapper level, only rearrange. But with 3 sources this question arises.

And I think this is a Pandora's box of sorts.

4) This leads to the most tough question for me: doesn't this sort of transformation be done at the relation, not a mapper?
Why don't union of those data at the query level, made them unique etc.? I see here is no strict border, but...

Not so simple

**Comment by c0** [comment]
@nepalez Yeah, I was afraid it'd create oddities and do more harm than good :(

As a "solution", I ended up using the `model` method (since it receives the entire tuple). This is very much a hack and I would not recommend it, but wanted to throw it out there in case there's a better way.

```ruby
class FooBarBazMerger
  def self.new(tuple)
    tuple.merge({
      name: tuple[:foo] || tuple[:bar] || tuple[:baz]
    })
  end
end

# inside the mapper
model FooBarBazMerger
```

**Comment by nepalez** [comment]
@c0 I don't think your solution to be a hack. I agree to @AMHOL the domain model is a right place to do this transformation.

However I like your syntax in principle. In a couple of days I'll implement it in the [faceter's `create` command](https://github.com/nepalez/faceter#instantiating-models). Then we could look at it and decide whether it could/would/should be translated to rom mappers.

**Comment by c0** [comment]
@nepalez cool. I'm interested to see how it plays out.

The part that feels like a hack to me is where `.new` is overwritten and returns tuple, rather than an instance of the class. This goes against expectations.

**Comment by nepalez** [comment]
Ah, yes. Maybe you'd better do it a module utility method, because you don't need to instantiate an object of your class. All in all this is a domain layer, not the datastore.

**Comment by kwando** [comment]
You cannot use a module with a new method there, rom does a type check in the model method and it expects a Class.

**Comment by kwando** [comment]
In recent versions of ROM one can achieve the desired output with this mapper definition.

```ruby
 step{
    wrap(:tags){
      attribute('tag1')
      attribute('tag2')
    }
  }

  step{
    attribute(:tags){ |h| h.values }
  }
```

**Comment by solnic** [comment]
I copied this issue to rom-mapper repo https://github.com/rom-rb/rom-mapper/issues/11
