### ISSUE TITLE
Unwind array

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#200]
Mapping
````javascript
{
  "item": "item1",
  "tags": ["hello", "world"]
}
````
to
````javascript
[
  {
    "item": "item1",
    "tag": "hello"
  },
  {
    "item": "item1",
    "tag": "world"
  }
]
`````
I'm not sure what I want this for though..  the ```Hash``` to ```Array``` conversion might be tricky.. maybe I'm just thinking to much about the mongodb aggregation pipeline now. 
Feel free to close if you do not think this mapping makes sense.

**Comment by solnic** [comment]
This is basically an `ungroup` operation. We could consider adding it but just like you I don't see any use cases for that now.

**Comment by nepalez** [comment]
I know the use case. It is for requesting denormalized data from non-sql (cassandra, mongo etc.) that supports collections, normalizing them via mapper and moving to sql.

Pretty weird case, but existing

**Comment by solnic** [comment]
Let's do it then. ROM must be the most advanced data mapper in Ruby after all \o/

**Comment by nepalez** [comment]
Will do it the next week

**Comment by nepalez** [comment]
Transformation is implemented as `unfold`:

```ruby
class UserMapper < ROM::Mapper
  unfold :tag, from: :tags
end
```
