### ISSUE TITLE
Allow Array defaults on Postgres array columns

### ISSUE THREAD

**Issue by schwern** [rom-rb/rom#203]
It would be nice if one could specify defaults on Postgres array columns as Ruby arrays.

    column :titles, 'varchar[]', default: []

This solves two problems.  First, `default: []` is currently ignored with no warning.  The column will wind up with no default.

Second, if it has a not null constraint auto_validations will not see it has a default and do a presence validation.  auto_validations looks only for a ruby_default (possibly a bug).  This makes it difficult to use auto_validations with Postgres arrays.

**Comment by schwern** [comment]
Sorry, I somehow posted this to the wrong repository.

**Comment by gotar** [comment]
It's good repository we collect here all issue

**Comment by schwern** [comment]
I'll reopen it then.

**Comment by schwern** [comment]
[In a related issue](https://github.com/jeremyevans/sequel/issues/989), @jeremyevans said no to the idea.  Or rather the impression I got was transparent PG<->Ruby array translation has to work everywhere or nowhere.

**Comment by AMHOL** [comment]
@schwern can you please expand on "wrong repository", when @gotar said we use this repository to collect all issues, he meant ROM issues, and probably assumed you intended to report this in the rom-rb/rom-sql repository, is that the case? This project is not affiliated with Sequel, it's just a dependency.

**Comment by schwern** [comment]
Exactly, I meant to report this to Sequel.  I'm not sure how I landed here.
