### ISSUE TITLE
Add JSON adapter

### ISSUE THREAD

**Issue by drewda** [rom-rb/rom#205]
Would it be possible to add a JSON adapter? This could potentially be useful to situations where data files are shared amongst libraries in Ruby, Node, Python, etc.

**Comment by solnic** [comment]
What would it do specifically?

**Comment by drewda** [comment]
Persist object data to JSON files, as an alternative to YAML or CSV formats.

**Comment by solnic** [comment]
Ah OK so we're talking about a file-based adapter targeting json. Yes this
sounds good. It would be very similar to yaml/csv adapters.

**Comment by drewda** [comment]
Great, thank you for considering this.

**Comment by lukeses** [comment]
I will work on this issue.

**Comment by rolfb** [comment]
@lukeses I've done some initial work in https://github.com/rom-rb/rom-json, but writing is still missing. Is that something you'd care to look into?

**Comment by AMHOL** [comment]
Think it would be better to have a `rom-file` adapter, then plugin an encoder/decoder each would take a string and convert to the required format, kind of like how rom-http will work

**Comment by solnic** [comment]
Yeah that is the plan actually. Think we're getting there with csv yaml and
now json adapters having so much in common.

**Comment by solnic** [comment]
Closing this one as we have rom-json now :boom:
