### ISSUE TITLE
calling mapper for update commands do not work

### ISSUE THREAD

**Issue by gotar** [rom-rb/rom#209]
```ruby
require 'rom'

ROM.setup(:memory)

class User
  attr_reader :name, :age

  def initialize(attributes)
    @name, @age = attributes.values_at(:name, :age)
  end
end

class Users < ROM::Relation[:memory]
end

class UserMapper < ROM::Mapper
  relation :users
  register_as :entity

  model User

  attribute :name
  attribute :age
end

class CreateUser < ROM::Commands::Create[:memory]
  register_as :create
  relation :users
  result :one
end

class UpdateUser < ROM::Commands::Update[:memory]
  register_as :update
  relation :users
  result :one
end

rom = ROM.finalize.env

user1 = rom.command(:users).as(:entity).create.call(name: "Joe", age: 17)
user2 = rom.command(:users).as(:entity).update.set(name: "Jane", age: 18)
puts user1.class, user2.class # => User, Hash
```

**Comment by solnic** [comment]
Does it work when you use `call` instead of `set`?

**Comment by gotar** [comment]
Yeap, it work.

**Comment by solnic** [comment]
OK the fix is simple, add `set` alias to `Command::Composite` but this makes me think we should always just use `call`/`[]` :/

**Comment by solnic** [comment]
I'd say we should deprecate aliases on commands and stick to `#call` and `#[]`. Thoughts? /cc @aflatter @splattael @maetl @cflipse

**Comment by gotar** [comment]
yeap those set was sth strange, different then we have in other places, using everywhere `#call` will be a lot better

**Comment by maetl** [comment]
> I'd say we should deprecate aliases on commands and stick to #call and #[]

What was the original purpose of the aliases? To make the API more ‘verb-oriented’ or something along those lines?

**Comment by solnic** [comment]
To make it feel less awkward. With the opposite result :)

**Comment by cflipse** [comment]
I'm good with it.  I tend to prefer "single entry" command objects use `call` anyway, just for the proc compatibility

**Comment by splattael** [comment]
:+1: for `call`
