### ISSUE TITLE
Allow specifying additional ON criteria for joins

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#211]
This _could_ be a documentation problem, and I'm missing things in the code, but I don't currently think so.

I need to be able to specify additional criteria within a JOIN command; right now the many_to_many command only appears to link by matching ids.  In addition to matching IDs, I need to be able to specify additional column restrictions.  (think:  state column, or "type" for dealing with a polymorphic association)

This is _not_ the same thing as adding a where clause to the end of the query, at least in the case of a left join.  While I can drop down to raw Sequel to get the effect, the query ends up breaking because all the table aliases and other logic from the association_join are lost.

**Comment by aflatter** [comment]
@cflipse I ran into the same thing literally minutes ago. The `:conditions` option on the association class methods does not seem to have any effect.

**Comment by solnic** [comment]
For now you can user sequel's `graph` directly. We're missing support for many extra options that Sequel API has.

**Comment by solnic** [comment]
I'm not sure how to add additional `ON` criteria but I added support for `:conditions` and setting custom association name. See referenced commit.

**Comment by solnic** [comment]
OK now I know how to do it I just need to know what the interface should be. Any ideas?

**Comment by cflipse** [comment]
Unfortunately, `where` isn't the same as `join ... on` for outer join scenarios; there really does need to be a way of handling the `on` conditions specifically.

`select * from users left join tasks on tasks.user_id = user.id and tasks.state = 'active'` is different than
`select * from users left join tasks on tasks.user_id = user.id where tasks.state = 'active'` ... the former gives back all users, with their active tasks.  The latter gives back only users with active tasks.


From what I can make out, additional join conditions could just  get added to the graph call here:
https://github.com/rom-rb/rom-sql/blob/4a16c3c0553c1205c515f8a7f3f427236ad31660/lib/rom/sql/relation/associations.rb#L100 by having the join_keys include the additional criteria  (well, there and the other spots that graph is called)

**Comment by solnic** [comment]
I know how to do it. It's gonna be messy for `many-to-many` probably. Any idea how the interface should look like?

``` ruby
one_to_many :tasks, on: { title: 'Blah' }
```

??

**Comment by cflipse** [comment]
That works for me.

We may or may not want to just let that completely subsume all of the FK/join key specification that exists currently; I'm not sure how nice it looks with both:

```
one_to_many :tasks, key: :user_id, on: { state: 'active' }
```
vs
```
one_to_many  :tasks, on: { user_id: :id, state: 'active }
```

I think I'm okay with either.  Maybe the mental gymnastics required to figure out which direction the keys go in `one_to_many` vs `many_to_one` argue for keeping the key paramter.  I wouldn't eliminate the `on` nest though, I think that clarity level is needed.

**Comment by solnic** [comment]
Done [here](https://github.com/rom-rb/rom-sql/commit/7028f3b38c002e1e306636f5d074ecd2f82124ec)
