### ISSUE TITLE
commands aren't surviving a reload

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#215]
```ruby
$ bin/rails c
Loading development environment (Rails 4.2.1)
irb(main):001:0> ROM.env.commands.entries.count
=> 7
irb(main):002:0> reload!
Reloading...
=> true
irb(main):003:0> ROM.env.commands.entries.count
=> 0
irb(main):004:0>
```

**Comment by cflipse** [comment]
Umm, seems localized to a specific app.  Still not sure what's going on, but at least it's not universal.

**Comment by cflipse** [comment]
* it only occurs on one app
* in that app, ONLY commands fail to reload
* Setup#command_classes is empty
* I checked, they're in the right directory
*they _are_ reparsed each time reload is fired (a 'puts' _does_ output)
* adding output to Command.inherited only fires on on initial load, NOT on reload
* calling ROM.register_command self in the command class does add it to the command_classes array

So .... it boils down to the 'inherited' hook not triggering, because ... reasons. I'm at a loss for why it wouldn't fire, but just for the commands.  Probably because the class isn't getting unloaded first, but ...

**Comment by cflipse** [comment]
Down to:

The generators were producing commands under:  `app/commands/users/create`, but the class names were `UserCommands::Create` ... because of this difference, Rails did not recognize the commands as auto-loadable, and did not add them to the correct ActiveSupport::Dependencies array.

When reloading, AS clears the contents of that array, undefining each constant.  ROM-reloads every file in it's directories on reload, so updates were being caught ... but the `inherited` hook was not triggering, because the class already existed; therefore the commands were not being registered in the new env.

I've fixed the generator, but existing code will have to be dealt with; probably by being moved.  Sooner a new release happens, the better.

**Comment by cflipse** [comment]
This is fixed, but we'll want to cut a new release of rom-rails soon, to get this fix out in the wild.

**Comment by solnic** [comment]
OK let’s fix remaining issues (or at least try) and push rom-rails next
week :)

**Comment by cflipse** [comment]
sounds good.
