### ISSUE TITLE
ROM::Rails uniquness validation does not implement scopeing

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#217]
There's an option in Rails' uniqueness validations to limit the checks to a particular scope.  From what I can see, that option is not being applied.

```ruby
class TaskValidator
  # ....
  validates :name, uniqueness: { scope: :user, allow_nil: true }
end
```

the above should work, but there's currently no way to narrow the relation being checked.

**Comment by solnic** [comment]
What does this option do in AR? Run validation on `Tasks.user` scope?

**Comment by cflipse** [comment]
It filters the query, so that it only considers records with the same value in the `user` field.

if `{ name: "Be Cool", user: "Joe" , deadline: "always"}` already eixsts, then
`{name: "Be Cool", user: "Joe", deadline: "tomorrow"}` would be invalid, but
`{name: "Be Cool", user: "Mark", deadline: "always" }` would validate.

Currently, both would fail validation.

**Comment by solnic** [comment]
This is now done via rom-rb/rom-rails#36
