### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#219]
the internal adapter component, currently called a Repository, is not an example of the repository pattern, and could cause confusion  when discussing ROMs place in the overall storage arcitecture  of an application.

It would be better if this component had a different name.  I'm not terribly sure _what_ that name is, right now ... reasonable options could include `Datastore` or `Gateway`  but I'm open to other ideas.

**Comment by solnic** [comment]
I'm leaning towards `Datastore` because it would play nice with `Dataset`. OTOH only exposes access to datasets, so hmmm maybe `Gateway`? As in a gateway to access datasets?

**Comment by splattael** [comment]
I like `Gateway`!
Should we deprecate the usage of `Repository` somehow to make the transition easier?

**Comment by solnic** [comment]
Yes that's the plan

**Comment by maetl** [comment]
`Gateway` is okay from my perspective.

**Comment by solnic** [comment]
Yeah, like gateway to another realm, gateway to another dimension or just gateway to postgresql ;)

Anyhow, do you think it's reasonable to schedule this change for 0.7.0? It's a massive rename + deprecate work but shouldn't be hard, just tedious. Hmm.

**Comment by cflipse** [comment]
Yeah -- Gateway is the name for a (family) of patterns that are basically thin access to an external system.  Provide a focused internal api around a RestClient library, that sort of thing.  It actually fits our usage really well here.

I suspect it's reasonable to chase for 0.7.0, unless we're looking to release on Monday.  ;)

Transitionally, we need to add Gateway to the various lookups, add deprication warnings (is there a standard way of doing that?) for Repository, and update the linters.

**Comment by solnic** [comment]
I was thinking about May 20ish as the release date. I have to admit that this change would be very low on my personal priority list so help would be appreciated.

**Comment by solnic** [comment]
Oh and regarding deprecations: no, we don't have anything in place yet. I think we should put something together as deprecations is not something we'll manage to avoid after all.

**Comment by maetl** [comment]
Alternatives to `ROM::Gateway` I just thought of: `ROM::Store` or `ROM::Source`.

**Comment by solnic** [comment]
Can we shoot for 0.8.0 with this mass-rename/deprecation? I added `Deprecations` module to `rom/support` which can be used for this easily.

Are we done deciding on the name? I'm good with `Gateway` :)

**Comment by nepalez** [comment]
I like both the `ROM::Gateway` and `ROM::Source`

**Comment by solnic** [comment]
`Source` is a bit too vague, no?

**Comment by cflipse** [comment]
Just a bit.  :)

0.8 sounds good; I'll work on this during the week

**Comment by solnic** [comment]
That would be awesome. I actually start thinking about wrapping up 0.8.0 before RubyNation (June 12th). Stuff that's schedule for this release should be very time consuming...guides on rom-rb.org come first though, that's my current focus.

**Comment by cflipse** [comment]
PR for this: #243
