### ISSUE TITLE
default repo set to nil when another repo is registered under custom name

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#222]
Looks like Railtie sets up `nil` as the `:default` repo when there's no actual default repo configured.

**Comment by cflipse** [comment]
I'm not experiencing that; do we have reproduction steps?

**Comment by solnic** [comment]
Do you have a rails app where there's no `:default` repository and only custom one is set?

**Comment by cflipse** [comment]
Oh ... meaning nothing in the AR loaded configs.  No, I don't.  Misunderstood the description.  Carry on. :)

**Comment by solnic** [comment]
It's now fixed as we check if AR is present and only then we set default *if* it wasn't set already in an initializer.
