### ISSUE TITLE
Renaming `ROM::CommandRegistry#as` to `#map_to`

### ISSUE THREAD

**Issue by c0** [rom-rb/rom#235]
One of the things that's confusing as a new ROM user is that `#as` is used with a mapper. From the TODO example —

```ruby
class TaskMapper < ROM::Mapper
  relation :tasks
  model Task
end

class TasksRelation < ROM::Relation[:sql]
end
```

When I run —

```ruby
rom.relation(:tasks).as(:tasks)
```

It's not clear what the second `:tasks` is or where it comes from.

I would like to recommend it be renamed to be more descriptive like `map_to`. Open to other ideas.

```ruby
rom.relation(:tasks).map_to(:tasks)
```

**Comment by nepalez** [comment]
@co, actually the mapper can map data without any model at all -- to pure hash. That's why naming it after the model is not a good idea. Instead, you can explicitly define the name of the mapper:

```ruby
class TaskMapper < ROM::Mapper
  relation :tasks
  register_as :tasks
  model Task
end
```

**Comment by c0** [comment]
@nepalez I don't think the confusion is in the naming of the mapper, but that `#as` does not have any indication that it's using a mapper.

```ruby
rom.relation(:tasks).as(:tasks)

# as opposed to
rom.relation(:tasks).map_to(:tasks)

# or even
rom.relation(:tasks).mapper(:tasks)
```

**Comment by nepalez** [comment]
I see. As for me, I feel conformed with `as`, but maybe you're right.
I think the substantial part of the confusion is a lack of documentation. Feel it as a stimulus for myself to write it faster :)

**Comment by c0** [comment]
I agree that documentation is immensely useful, but it's better when the code is clear without it. Both are needed :)

**Comment by solnic** [comment]
`as` is an alias of  `map_with` and we still haven’t decided which one is
better :)

**Comment by c0** [comment]
@solnic good to know. I personally like `#map_with`

**Comment by solnic** [comment]
btw you can pass multiple mapper names there ie `rom.relation(:users).map_with(:entity, :view_presenter)` which for me is an awesome feature :D

**Comment by cflipse** [comment]
eh, I actually prefer `as` ... I want to get the results of this relation *as* a  `:user_with_tasks`  ... makes plenty of sense.

**Comment by solnic** [comment]
me to, it reads nice imo just like you said. I guess we need to make a decision and stick to just one for 1.0.0 :)

**Comment by maetl** [comment]
I prefer `as` too. Having `map_with` there as an alias is okay from my perspective. It’s potentially a more intricate API than it needs to be, but I can see uses of both for readability reasons, depending on the particular style of client code.

For example, Sequel aliases `where` and `filter`.

**Comment by c0** [comment]
The way I read `as` is that it's expecting a *noun*. i.e. the object/model you'll end up with. I see mappers more as *verbs* and transformative rather than an end result. So something like `rom.relation(:users).through(:entity, :view_presenter)` makes more sense.

At the end of the day, I'll follow the consensus. I've been a ruby dev for a number of years, but am new to rom-rb and just wanted to surface some things that may be difficult for newcomers :)

**Comment by solnic** [comment]
Let's see what people prefer and decide for 1.0.0 how it should be named. Closing this for now.

**Comment by c0** [comment]
Sounds like a plan. Thanks everyone for the feedback!
