### ISSUE TITLE
Nicer error messages when (miss)using combine

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#237]
If you forget to use combine on either a relation or mapper rom blows up with an unreadable Transport error.

```ruby
rom.relation(:users).as(:some_mapper_with_combine_block)
```

```ruby
rom.relation(:users).combine(tasks.for_users).as(:some_mapper_without_combine_block)
```

In general I expect some kind of ROM::MappingError instead of the Transproc errors leaking out.

**Comment by solnic** [comment]
Any ideas how to display the error so that it's relatively easy to figure out what went wrong?

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-mapper#17
