### ISSUE TITLE
Missing mapper does not raise an error

### ISSUE THREAD

**Issue by carlisia** [rom-rb/rom#251]
When a mapper is missing from the registry, it should throw an error. Instead, it is returning ```nil```.

```#<WidgetsController> » 4.2.1@2.2.0 rom.relation(:widgets).as(:widgets).one
NoMethodError: undefined method `call' for nil:NilClass```

**Comment by solnic** [comment]
The reason why it happens is that lazy relation sets its internal mapper
registry to an emtpy hash by default. A simple fix is to replace it with
MapperRegistry.new which raises an error when mapper is missing.
