### ISSUE TITLE
Scope relations' method resolution to direct classes

### ISSUE THREAD

**Issue by pnomolos** [rom-rb/rom#255]
This is mainly because Rails is stupid, but for example I was trying to do the following:

```ruby
# Other code omitted for brevity

class ProductsRelation < ROM::Relation[:sql]
  dataset :products
  register_as :products

  one_to_many :options, key: :product_id

  def with_options
    association_join(:options)
  end

  def by_id(id)
    where(id: id)
  end
end

# Let's get a Product with its Options!
rom.relation(:products).by_id(params[:product_id]).with_options.one!
```

Which raises an `ArgumentError` due to http://apidock.com/rails/Object/with_options - due to the use of `method_missing` to call the relation's methods it ends up calling the method on `Object` instead.

I'll work around it for now, but wondering if anything has been thought about in this regard?

**Comment by solnic** [comment]
Gah that's just...

Anyway, that method_missing will be gone prior 1.0.0. Each relation will have its own lazy-class that will decorate relation's methods to provide autocurry mechanism and so on.

Now you just gave me a reason to do it faster :)

**Comment by solnic** [comment]
Lazy with method_missing is gone so this is fixed too :)
