### ISSUE TITLE
Split rom into pieces

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#256]
rom gem reached ~2.5k LOC so it's becoming quite big. It is also harder to see it's decoupled and toolkit-oriented nature which is why it might be a good idea to break it down into smaller gems.

One way to do it would be:

* rom-core - essential low level APIs (options, class macros, FP apis, core abstract interfaces, adapter interfaces etc.)
* rom-relation - everything from `ROM::Relation` namespace
* rom-mapper - everything from `ROM::Mapper` namespace
* rom-command - everything from `ROM::Commands` namespace
* rom-env - setup API with `ROM::Env`
* rom - becomes a meta gem with default stack

The closer we are to 1.0.0 the more this should be discussed :)

**Comment by c0** [comment]
I like the idea of pulling these apart. It gives us an opportunity to show how to use the classes on their own without the DSL.

What do you think about pulling the DSL together in either `rom` or `rom-dsl`? (If it's possible). Or would this be covered by `rom-env`?

**Comment by solnic** [comment]
@c0 when you say `DSL` - what do you mean exactly? Setup DSL (`ROM.relation(:foo) {}` etc.) or in general DSLs that come with core classes (`Relation.gateway`, `Command.register_as` etc.)??

**Comment by c0** [comment]
Sorry, DSL isn't the right word.

I was wondering what it would look like to separate the pipeline/lazy API from instantiating the classes directly. (Mapper.build etc).

This may be implied by the list you have or it may be something not practical. :)

**Comment by errinlarsen** [comment]
I like the proposed split (rom-core, rom-relation, rom-mapper, and rom-command, with a 'rom' meta gem for delivering a default stack). I think rom-env needs some work. It feels like there are a couple pieces tied together in ROM::Env; namely, the registries and the setup DSL.

What if I want to implement my own mapper DSL, use the provided relation DSL, write my own setup DSL, and I already have some global-level registry solution that I'd like to add ROM components to?

**Comment by cflipse** [comment]
The split makes sense to me; especially if it surfaces enough of an interface to be able to get a non-global ROM.env replacement.

**Comment by solnic** [comment]
Yeah I feel like the time is right already...I mean after 0.8.0 release. So 0.9.0 would be a huge release with gems split and lots of internal clean up and getting rid of global setup and implicit registration etc.

**Comment by AMHOL** [comment]
Defo :+1: for this, rom-mapper will be particularly useful stand-alone

**Comment by solnic** [comment]
So, having second thoughts on `rom-commands` and `rom-relation` simply because those are abstract interfaces, practically speaking. Even though you can use `ROM::Relation.new([])` it still doesn't seem to be useful enough to justify having a separate gem for that.

Maybe we should have `relation` and `commands` part of `rom-core` as abstract interfaces required by adapters?

**Comment by solnic** [comment]
After some further chats I think this would make most sense:

* `rom-core` - support libs, core APIs + `environment` + `relation` + `command`
* `rom-mapper` - self explanatory
* `rom` becomes `rom-core` + `rom-mapper` meta gem

**Comment by cflipse** [comment]
:+1: Looks good to me.

Though, I'll note with amusement that this means that the core of `Ruby Object Mapper` does not, in fact, contain a mapper.  :D

**Comment by solnic** [comment]
![memimg](http://cdn.meme.am/instances/500x/63927952.jpg)

**Comment by AMHOL** [comment]
https://www.youtube.com/watch?v=ggV6LoYaQmg

**Comment by solnic** [comment]
Done. we ended up with rom and rom-rb/rom-support and rom-rb/rom-mapper
