### ISSUE TITLE
Embedded doesn't support from

### ISSUE THREAD

**Issue by dekz** [rom-rb/rom#263]
We may be incorrectly using the the embedded syntax, but we can't use the `from:` option when passing in a mapper when using embedded (and some others).

```ruby
embedded :cats, from: 'CatDetails', mapper: CatMapper
```

We expected that syntax to work in conjunction with a CatMapper:
```ruby
class CatMapper
  model Cat
  attribute :name, from: 'sillyCateKeyName'
end
```

The following code seems to work, but we would prefer to pass mapper instead of always nesting in a block.

```ruby
    embedded :cats, from: 'CatDetails' do
      model Cat
      attribute :name, from: 'sillyCateKeyName'
    end
```

It just seems that the `from:` isn't being passed through in the embedded dsl method.

Is this intended usage, or have I completely missed something obvious?

**Comment by dekz** [comment]
Ugh, silly me. Looks like you guys have already fixed this in f46e4f9e415c5606fc0e39c2474aeec83a912d16.

**Comment by solnic** [comment]
Sorry you've been affected by this :) We're pushing 0.8.0 tomorrow (unless some unexpected blockers are found).

**Comment by dekz** [comment]
No worries, cheers for that!

**Comment by dekz** [comment]
I do have a quick question @solnic if you have a spare second. I'm trying to grok the usage of Mapping and how they relate to, well, Relations. 

I will try and use the examples from the tests that I have been seeing lately, and maybe once I figure it out I'll write up a quick wiki on this repo to help explain it to the next person.

Let's say I have a list like this:
```ruby
response = {
  task_list: 1,
  tasks: [
    { user: 'jacob', task_id: 1, title: 'do something' },
    { user: 'jacob', task_id: 2, title: 'do something else' },
] }
```

I want to map the data in a way that isn't a 1:1 translation of Hash into ruby models. Let's say this is a legacy mapping of data and translated into the Model of Users and Tasks.

```ruby
# Models
class TaskList
  attribute :id
  attribute :user
end

class User
  attribute :name
  attribute :tasks
end

class Task
  attribute :user
  attribute :title
  attribute :id
end
```

```ruby
class TaskListMapper < ROM::Mapper
  model TaskList
  register_as :task_list # Not 100% sure what this does as it isn't listed in the generators?

  attribute :id, from: :task_list
  embedded :user, from: :tasks do
    model User
    attribute :name, from: :user
    group :tasks, on: { name: :name } do
      attribute :title
    end
  end
end

```

I'm missing something that helps me grok all this together, any chance you could push me in the right direction?

**Comment by nepalez** [comment]
In `0.8.0` to convert tuple:

```ruby
{
  task_list: 1,
  tasks: [
    { user: 'jacob', task_id: 1, title: 'do something' },
    { user: 'jacob', task_id: 2, title: 'do something else' },
  ]
}
```

into the output:

```ruby
{
  id: 1,
  user: {
    name:  "jacob",
    tasks: [
      { title: "do something",      id: 1 },
      { title: "do something else", id: 2 }
    ]
  }
}
```

you could do this mapper:

```ruby
class UserMapper < ROM::Mapper
  relation :users
  register_as :users

  attribute :id, from: :task_list

  wrap :user do
    attribute :user
    group :tasks do
      attribute :id, from: :task_id
      attribute :title
    end
  end
end
```

The only difference from your example is that while grouping into tasks, the mapper will extract the `:user` from the list.

This is not a bug, but a sort of a policy IMHO. ROM mapper doesn't create the data, only rearranges the existing ones.

I think, populating tasks with the name of a user they relates to could be the responcibility of your domain model, not the ROM.

**Comment by dekz** [comment]
Thanks for the reply @nepalez, the requirement of having user duplicated is unnecessary and I guess I understand the principle of never duplicating data.

I did try your example on `0.8.0` and it doesn't seem to be able to infer the grouping on users.

```ruby
require 'rom'
require 'virtus'

Entity = Virtus.model(coerce: false)

class User
  include Entity

  attribute :id
  attribute :name
  attribute :tasks
end

class Task
  include Entity

  attribute :id
  attribute :name
  attribute :user
end

class UserMapper < ROM::Mapper
  relation :users
  register_as :users

  attribute :id, from: :task_list

  wrap :user do
    attribute :name, from: :user
    group :tasks do
      attribute :id, from: :task_id
      attribute :title, from: :task
    end
  end
end

response = {
  task_list: 1,
  tasks: [
    { user: 'jacob', task_id: 1, task: 'do something' },
    { user: 'jacob', task_id: 2, task: 'do something else' },
    { user: 'steve', task_id: 2, task: 'do something else' },
    { user: 'steve', task_id: 1, task: 'do something' },
] }

mapper = UserMapper.build
prop = mapper.call [ response ]
#=> [{:tasks=>
#   [{:user=>"jacob", :task_id=>1, :task=>"do something"},
#    {:user=>"jacob", :task_id=>2, :task=>"do something else"},
#    {:user=>"steve", :task_id=>2, :task=>"do something else"},
#    {:user=>"steve", :task_id=>1, :task=>"do something"}],
#  :id=>1,
#  :user=>{:name=>nil, :tasks=>[]}}]
```

Is the syntax missing a parameter that tells ROM how or what to group on?

**Comment by solnic** [comment]
This one's tricky. I don't have time now but I'll take a look later today and try to figure it out :)

**Comment by nepalez** [comment]
D'oh, sorry, this was my fault. I turn you to the wrong path.

The problem is that there's no way to group users after wrapping, because it groups mapped items, that are already different. Yes, this is tricky, i need some time to sort it out.

**Comment by nepalez** [comment]
@dekz This would work:

```ruby
require "rom"

ROM.setup :memory

class Users < ROM::Relation[:memory]
  dataset :users
  register_as :users
end

class FirstMapper < ROM::Mapper
  register_as :first
  relation :users

  attribute :id, from: :task_list
  unfold :tasks
end

class SecondMapper < ROM::Mapper
  register_as :second
  relation :users

  attribute :id
  unwrap :tasks do
    attribute :user
    attribute :task_id
    attribute :title
  end
end

class ThirdMapper < ROM::Mapper
  register_as :third
  relation :users

  group :tasks do
    attribute :id, from: :task_id
    attribute :title
  end
end

class ForthMapper < ROM::Mapper
  register_as :forth
  relation :users

  wrap :user do
    attribute :name
    attribute :tasks
  end
end

rom = ROM.finalize.env

rom.relations.users.insert(
  task_list: 1,
  tasks: [
    { user: 'jacob', task_id: 1, title: 'do something'      },
    { user: 'jacob', task_id: 2, title: 'do something else' }
  ]
)

rom.relation(:users).as(:first, :second, :third, :forth).to_a
```

Results step-by-step:

```ruby
# => [{:tasks=>{:user=>"jacob", :task_id=>1, :title=>"do something"}, :id=>1}, {:tasks=>{:user=>"jacob", :task_id=>2, :title=>"do something else"}, :id=>1}]

rom.relation(:users).as(:first, :second).to_a
# => [{:id=>1, :user=>"jacob", :task_id=>1, :title=>"do something"}, {:id=>1, :user=>"jacob", :task_id=>2, :title=>"do something else"}]

rom.relation(:users).as(:first, :second, :third).to_a
# => [{:id=>1, :user=>"jacob", :tasks=>[{:id=>1, :title=>"do something"}, {:id=>2, :title=>"do something else"}]}]

rom.relation(:users).as(:first, :second, :third, :forth).to_a
# => [{:id=>1, :user=>{:tasks=>[{:id=>1, :title=>"do something"}, {:id=>2, :title=>"do something else"}]}}]
```

**Comment by nepalez** [comment]
@solnic In the example above we could not use 4 (!) mappers. Instead we could use a sequence of commands within the only mapper:

```ruby
class FirstMapper < ROM::Mapper
  register_as :first
  relation :users

  attribute :id, from: :task_list

  unfold :tasks

  unwrap :tasks do
    attribute :user
    attribute :id, from: :task_id
    attribute :title
  end

  group :tasks do
    attribute :id, from: :task_id
    attribute :title
  end

  wrap :user do
    attribute :name
    attribute :tasks
  end
end
```

The only thing why this doesn't work is that mapper is too lazy. It doesn't remembers that attributes were renamed. I wonder, whether we could do something here?

**Comment by solnic** [comment]
haha! I thought today "well, we need to have a way to specify a sequence of transformations in a single mapper to avoid having to use multiple mappers"

so I guess we should just do it, question is: how the dsl should look like?

``` ruby
class SequenceMapper < ROM::Mapper
  sequence do
    # stuff defined here will be executed one-by-one
  end
end
```

??

**Comment by nepalez** [comment]
The wonderful part of all of this is my last example is already works (well, except for renaming attributes).

**Comment by nepalez** [comment]
Maybe this would more "natural":
```ruby
class FirstMapper < ROM::Mapper
  register_as :first
  relation :users

  step do
    attribute :id, from: :task_list
    unfold :tasks
  end

  step do
    unwrap :tasks do
      attribute :user
      attribute :task_id
      attribute :title
    end
  end

  step do
    group :tasks do
      attribute :id, from: :task_id
      attribute :title
    end
  end

  step do
    wrap :user do
      attribute :name, from: :user
      attribute :tasks
    end
  end
end
```

On every step the sequence `compose --> preprocess --> process primitives --> postprocess` would be done, so at the first of the next step we could do the same data as it were mapped before.

**Comment by solnic** [comment]
hmm yeah I think I like that

**Comment by dekz** [comment]
@nepalez thanks for that mate, it looks really good. Having those steps or sequences would also be a really good idea I feel. I am willing to try and help implement this if you like.

**Comment by solnic** [comment]
@dekz that would be awesome; it should be a simple addition as underlaying pieces are reusable. The contract should be that if there are steps, we only build up a mapper from those, if there are steps + top-level definition, we raise an error. step block would simply use `AttributeDSL` to gather attributes and store them in "steps" array and then you just build up each step using transproc compiler and compose into a single transformer and :tada:

**Comment by nepalez** [comment]
@solnic should this `step` to be included to the next release?

**Comment by solnic** [comment]
I want to push 0.8.0 later today but I think I won’t make it > - <. Steps
could be added in 0.8.1 or 0.8.0 if we can make it.
