### ISSUE TITLE
ROM::Commands::Result::Success#success?

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom#266]
I'd like to have #failure? and #success? methods available on Commands::Result

**Comment by AMHOL** [comment]
:+1: I've thought about this before too

**Comment by kwando** [comment]
It might not be very "functional" to have query those methods, but I often end up with "if result.error" code anyway

**Comment by solnic** [comment]
This stuff ain't finished. We're looking at integration with Unsound gem from @pdswan

**Comment by solnic** [comment]
OK let's add those methods. Any volunteers? :)

**Comment by Snuff** [comment]
@solnic Hi! I can do it) I'm trying to use ROM in my project and I need use this feature:) I think I can realize it in 1 week.

**Comment by Snuff** [comment]
Sorry for delay, I had a deadline on my work, I'm working on this issue.

**Comment by solnic** [comment]
This was done in #310
