### ISSUE TITLE
Renaming nested attributes

### ISSUE THREAD

**Issue by nepalez** [rom-rb/rom#269]
Maybe we need some method to rename nested attribute from:

```ruby
# from:
[{ name: 'joe', contact: { address: 'joe@doe.com' } }]
# into: 
[{ name: 'joe', contact: { email: 'joe@doe.com' } }]
```

At first I thought of a block syntax like:

```ruby
attribute :contact do
  attribute :email, from: :address
end
```

But the block is already reserved for value coersion. And what about arrays:

```ruby
# from:
[{ name: 'joe', contacts: [{ address: 'joe@doe.com' }] }]
# into:
[{ name: 'joe', contacts: [{ email: 'joe@doe.com' }] }]
```

So I have no good solution for DSL for now.

---

Actually I'm already threatened by the gazillion of methods that either already added to the mapper or can be added in future.

Maybe we should stop and think of some convention for the DSL to keep its further development under control.

**Comment by dekz** [comment]
It is a little weird that attribute block is different from everything else. Maybe coercion syntax should change and attribute can follow the same convention regarding the blocks.

**Comment by nepalez** [comment]
What I'd propose is the following approach (maybe this should be applied outside of ROM at all as an external mapper)

1) Every DSL leaf method is NOT a description of the result, but a description of transformation:

`rename :foo, to: :bar` instead of `attribute :bar, from: :foo`
`wrap :foo, to: :bar` instead of `wrap bar: [:foo]`
`unwrap :foo, from: :bar` instead of `unwrap bar: [:foo]`

etc.

One transformation per step. No nested transformations at all

2) Use `attribute` and `array` with a block to access nested values:

```ruby
array do
  attribute :foo do
    array do
      rename :bar, to: :baz
    end
  end
end

# from
[{ foo: [{ bar: 1 }, { bar: 2 }] }]

# into
[{ foo: [{ baz: 1 }, { baz: 2 }] }]
```

Here we doesn't nest transformations (they are already leaf), but data structure to access the level to apply a transformation.

3) Then we'll need only those types of transformations

* rename keys (see above)

* remove keys

```ruby
[{ foo: 1, bar: 2 }]
```

```ruby
array
  remove :foo
end
```

```ruby
[{ bar: 2 }]
```

* create new values from the existing ones with block

```ruby
[{ foo: 1, bar: 2 }]
```

```ruby
array
  create :qux, from: [:foo, :bar] do |foo, bar|
    foo + bar
  end
  remove :bar
end
```

```ruby
[{ foo: 1, qux: 3 }]
```

* wrap/unwrap *values* applied to any level:

```ruby
[{ foo: [{ bar: 1, baz: 2 }] }]
```

```ruby
array do
  attribute :foo
    wrap :qux # means 'wrap value of [{ foo: ? }]' to qux
  end
end

# [{ foo: { qux: [{ bar: 1, baz: 2 }] } }]
```

```ruby
array do
  attribute :foo
    array do
      wrap :qux # means 'wrap each tuple of [{ foo: [?] }]' to qux
    end
  end
end

# [{ foo: [{ qux: { bar: 1, baz: 2 } }] }]
```

* group/ungroup lists also applied to any level:

```ruby
# [{ foo: [{ bar: 1, baz: 2 }, { bar: 1, baz: 3 }] }]
```

```ruby
array do
  attribute :foo
    array
      group :baz, to: :qux
    end
  end
end
```

```ruby
# [{ foo: [{ bar: 1, qux: [{ baz: 2 }, { baz: 3 }] }] }]
```

**Comment by dekz** [comment]
Being able to reach down into nested structures to map at that level is definitely something we need to consider.

My current workaround is to apply a mapper at that level using the attribute coercion, ie:

```ruby
attribute :foo do |f|
  #[{ bar: 1 }, { bar: 2 }]
  BarMapper.build.call(f)
end
```

This workaround is not something that feels great.

**Comment by solnic** [comment]
there's `embedded` which does exactly that:

``` ruby
embedded :foo, type: :hash do
  attribute :baz, from: :bar
end
```

**Comment by nepalez** [comment]
Ahh! Need to document this

**Comment by nepalez** [comment]
Mentioned embedded in mappers guide.
