### ISSUE TITLE
Adding AR timestamps via command plugin

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom#271]
Hi,

I tried to implement support of AR timespamp fields (updated_at + created_at) via command plugin:
```ruby
module CommandPlugins
  module ActiveRecordTimestamps
    def insert(tuples)
      now = Time.zone.now
      tuples_with_timestamps = tuples.map do |tuple|
        tuple.merge(created_at: now, updated_at: now)
      end
 
      super(tuples_with_timestamps)
    end
 
    def update(tuple)
      super(tuple.merge(updated_at: Time.zone.now))
    end
  end
end
 
ROM.plugins do
  adapter :sql do
    register :timestamps, CommandPlugins::ActiveRecordTimestamps, type: :command
  end
end
```

But I use Postgresql and therefore my plugin methods were overridden by DB-specific extension:
https://github.com/rom-rb/rom-sql/blob/e499585c293f640c300a2b62ffb210a6633d92eb/lib/rom/sql/commands_ext/postgres.rb

Should such extensions be implemented via plugin API? Should inheritance chain be manageable (like rack's middlewares)? Or should I just overload #execute method?

**Comment by gotar** [comment]
For me it should be set in `input` part of Command

**Comment by flash-gordon** [comment]
Like that?
```ruby
module CommandPlugins
  module ActiveRecordTimestamps
    class HashWithTimestamps
      def self.[](*args)
        tuple = Hash[*args]

        now = Time.zone.now

        if tuple[:created_at]
          tuple.merge(updated_at: now)
        else
          tuple.merge(created_at: now, updated_at: now)
        end
      end
    end

    def self.included(base)
      super

      base.input HashWithTimestamps
    end
  end
end
```

**Comment by gotar** [comment]
Yes if you insist on plugin. But probably input from command will overwrite it.

**Comment by flash-gordon** [comment]
Ok, I'll keep it in mind. Also my implementation changes behavior of `input#[]` so it's not a pure function anymore.

Thank you!

**Comment by solnic** [comment]
In rom-rails we just added it to `ROM::Model::Attributes` extension that works nicely with commands. You could do the same as @gotar suggests.

**Comment by flash-gordon** [comment]
Wow, right in time (=
