### ISSUE TITLE
Create of memory adapter does not set id

### ISSUE THREAD

**Issue by ThijsWouters** [rom-rb/rom#273]
Or how would I set it automatically in memory? I want to mimic a sql database where the id field is set in the database.

```ruby
require 'rom'
require 'rom/memory'

ROM.setup(:memory)

ROM.relation(:users)
ROM.commands(:users) do
  define(:create)
end

ROM.finalize

ROM.env.command(:users).create(name: 'Test Testington').call
user = ROM.env.relation(:users).first

user[:id].nil?
```

**Comment by nepalez** [comment]
D'you mean "doesn't set it authomatically"? It shouldn't

**Comment by AMHOL** [comment]
I did it like this: https://github.com/AMHOL/rom-playground/blob/master/lib/core/commands/create_user.rb

**Comment by ThijsWouters** [comment]
@nepalez When I create an entity, I want to omit the id. So that in the real system the id is assigned by the database.
@AMHOL That looks like it is a possibility. But, how would I let the database choose the primary key.

**Comment by AMHOL** [comment]
@ThijsWouters there is no database with the in-memory adapter

**Comment by nepalez** [comment]
@ThijsWouters you have to look at the [rom-sql](https://github.com/rom-rb/rom-sql), that is wrapped around the `Sequel`. Using `Sequel` scheme you can define primary key, foreign key etc.

The `rom/memory` is a simple in-memory storage. There is no concept of primary key. As @AMHOL noticed above, you can provide your own, but it it totally up to you.

**Comment by ThijsWouters** [comment]
@nepalez I know about that gem. But my project is still very new, and I don't want to pin myself to an implementation of a data source just yet. I will go with @AMHOL's solution for now.

Is this something that can be added?

**Comment by nepalez** [comment]
No, I think adding the `uuid` as @AMHOL proposed is a sort of golden standard for `rom/memory`.

**Comment by solnic** [comment]
You could build a plugin which generates a UUID for commands.

**Comment by ThijsWouters** [comment]
I created a plugin that does exactly this: https://github.com/ThijsWouters/rom-generated_id

**Comment by solnic** [comment]
Hah that's cool!
