### ISSUE TITLE
Rails 3.0.20 -- ArgumentError: ROM is not missing constant Commands!

### ISSUE THREAD

**Issue by kchien** [rom-rb/rom#274]
Using the following gems:
===

1. Rails 3.0.20
2. my rom-rails fork, using @cflipse's recent commit. So my Gemfile has this line for rom-rails:
`gem 'rom-rails', :require => false, :git => 'https://github.com/kchien/rom-rails.git', :branch => 'wip_lower_version_in_gemspec'`  I needed to use this fork because the gemspec requires rom 0.8 which has not been released yet.
3. rom 0.7.1
4. rom-yaml 0.1.0

Problem  
===

The test below works fine, but as soon as I define a `Command`, I get the stacktrace below.
    
My test:
===

```ruby
require 'test_helper'
require 'rom-rails'
require 'rom/commands/create'

class RomRailsTest < ActiveSupport::TestCase
  should 'work with older version of rails' do

    root = Pathname(__FILE__).dirname.join('..')

    path = "#{root}/fixtures/test_db.yml"
    setup = ROM.setup(:yaml, path)

    setup.relation(:users) do
      def by_name(name)
        restrict(name: name)
      end
    end

    setup.mappers do
      define(:users) do
        register_as :entity

        model name: 'User'

        attribute :name
        attribute :email

        embedded :roles, type: :array do
          attribute :name, from: 'role_name'
        end
      end
    end

module UserCommands
  class Create < ROM::Commands::Create[:yaml]
    relation :users
    register_as :create
    result :one

    # define a validator to use
    #     # validator TaskValidator
  end
end
    rom = setup.finalize
    jane = rom.relation(:users).as(:entity).by_name('Jane').first
    assert_equal jane.name, 'Jane'
  end
end

```

Stacktrace:
===

```
Error: test: RomRails should work with older version of rails. (RomRailsTest)
  ArgumentError: ROM is not missing constant Commands!
activesupport (3.0.20) lib/active_support/dependencies.rb:483:in `load_missing_constant'
activesupport (3.0.20) lib/active_support/dependencies.rb:183:in `block in const_missing'
activesupport (3.0.20) lib/active_support/dependencies.rb:181:in `each'
activesupport (3.0.20) lib/active_support/dependencies.rb:181:in `const_missing'
rom (0.7.1) lib/rom/command.rb:52:in `const_get'
rom (0.7.1) lib/rom/command.rb:52:in `adapter_namespace'
rom (0.7.1) lib/rom/command.rb:41:in `[]'
test/unit/users_test.rb:35:in `<module:UserCommands>'
test/unit/users_test.rb:34:in `block in <class:RomRailsTest>'
shoulda (2.11.3) lib/shoulda/context.rb:382:in `call'
shoulda (2.11.3) lib/shoulda/context.rb:382:in `block in create_test_from_should_hash'
activesupport (3.0.20) lib/active_support/testing/setup_and_teardown.rb:67:in `block in run'
activesupport (3.0.20) lib/active_support/callbacks.rb:429:in `_run_setup_callbacks'
activesupport (3.0.20) lib/active_support/testing/setup_and_teardown.rb:65:in `run'
===============================================================================
```

**Comment by solnic** [comment]
Maybe we're missing a require somewhere in ROM :/

**Comment by kchien** [comment]
@solnic I tried requiring many files, but I couldn't get past this error.  On the other hand, does my test setup look correct?

**Comment by solnic** [comment]
@kchien actually, I think this won't work because adapter must be setup prior defining any rom components, make sure it is and this problem should be gone

**Comment by kchien** [comment]
@solnic Thanks for your help.  If I remove the lines:

```ruby
module UserCommands
  class Create < ROM::Commands::Create[:yaml]
    relation :users
    register_as :create
    result :one

    # define a validator to use
    #     # validator TaskValidator
  end
end
```
then the test will pass.  However, being new to rom, I'm not quite sure when and where I should define my create command.  I tried placing it after `rom.finalize` but the problem still persisted.

**Comment by solnic** [comment]
Don't put them in test files, they are auto-loaded from `app/commands`

**Comment by kchien** [comment]
Thanks! That fixed the problem. I believe I may have uncovered another `undefined method` error, so I'll create a new issue.

**Comment by solnic** [comment]
To be able to define ROM components (relations and commands) you need to make sure that `ROM.setup` was called before that. rom-rails loads initializer where you need to set up configuration, then it calls `ROM.setup` with provided config and *then* it loads components from `app/#{relations,commands,mappers}`.

We do, however, need to raise a meaningful error in cases like yours, which I'm going to fix :)
