### ISSUE TITLE
Unquiness validation fails for updates

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#276]
When updating an existing record, the uniqueness validation check does not filter out the "current" relation, and therefore fails.

Need to add a `where id <> {id}` to the uniquness criteria used.

**Comment by solnic** [comment]
That's a bit tricky. `Relation#unique?` doesn't know if we're talking about an existing object or not. We also can't just assume `id` as the primary key. Maybe we could extend the validator so that we can configure different behavior for existing objects and new ones and set some defaults there.

**Comment by vrish88** [comment]
What about something like `validates :name, uniqueness: {primary_key: :id}`?

**Comment by cflipse** [comment]
That ... _might_ work.

in all honesty, I'm coming up against a slightly different situation.  I want to be able to validate uniquness for only a subset of actions, and I'm starting to think the "easiest" way might be to inject the relation (it's currently directly inferred, and so can only operate on the base)

Think:  A shopping list.  I want to guard against double adding milk if it's "to get" or "in cart", but I don't care about duplication in "already purchased"

Getting the `base_dataset` from #154 would do this, because I could just build a relation of "active" cart items (but would _not_ help with the subject of this ticket) ... other option is back to the buliding-block approach, and the validation becomes:

```ruby
validates :name, uniqueness: { relation: rom.relations(:cart_items).active.exclude(id: :id).active, message: "Already added #{name}" }
```

**Comment by vrish88** [comment]
I'm kinda still new to this so lemme know if I'm way off base... So validations in ROM are only done in the context of a Form right? So could we modify the form so that validations block could take a relation object as well as the name of a relation?

```ruby
class TaskForm < ROM::Model::Form
  validations do
    relation rom.relations(:cart_items).active.exclude(id: :id).active

    validates :name, uniqueness: { message: "Already added #{name}" }
  end
end
```

**Comment by cflipse** [comment]
Validations take place in the context of a command, not a form.  ROM-rails imports validations from rails, and builds up some nicities around the definition, but core rom has a validation concept.

What you suggest _could_ work, except that there are some holes in both suggested structures, around _correctly_ filling in data from runtime (ie, that `id: :id` bit isn't actually valid, and shouldn't really be so).

Setting a global relation for the uniqueness guard works is most cases, but breaks down when I want to have two uniqueness validations with different scopes:  a `task_name` that's unique to the `user_id`, but a `guid` that's globally unique, for example.  You'll still need to be able to specify a relation in the validation itself, in that case.  Which is, generally, what scope does, but I need a _little_ more than that still

**Comment by cflipse** [comment]
(and, note that what I'm considering a need for there is beyond what rails uniquness validation usually covers, so ...)

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-rails#45
