### ISSUE TITLE
running generators in the wrong order causes breakage

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#277]
If you run either the `rom:command` or `rom:mapper` generators before a relation exists, that generator will run fine.  However, _all_ subsequent rails commands will fail, as the generated commands/mappers attempt to reference the non-existant relation.

This could possibly be solved by defering the `ROM.finalize` call to first access of `ROM.env`

**Comment by solnic** [comment]
We now have a lazy-loaded env so this fixes it \o/
