### ISSUE TITLE
Relation confusion

### ISSUE THREAD

**Issue by tpitale** [rom-rb/rom#282]
`ROM.env.relation(:users)` vs. `ROM.env.relations.users` vs. `ROM.env.relations[:users` … the last two seem to be equivalent. The first wraps in a lazy.

The first responds to `as` to make use of mappers.

The last two respond to `insert` and `update` etc from rom-sql. The first does not.

Am I missing something … or is this just really confusing?

**Comment by tpitale** [comment]
The answer may very well be "just use commands everywhere".

**Comment by solnic** [comment]
`rom.relations` is a lower level sort-of private inferface. It returns barebone relation objects that are used by commands. Relations can implement full crud interface. Which happens in rom-sql but for cud commands should be used as it's the higher level interface of rom.

**Comment by tpitale** [comment]
May be something worth mentioning in the rom-sql docs … as I was trying to use what it says in the README there, and those are very similar (all coming from `env`). I wouldn't be surprised if that's confusing to others.

Or maybe it'll just be in a later rom-sql guide on using the commands they have built in to that gem?

Closing for now, let me know if you want me to do anything on this re: documentation.

**Comment by solnic** [comment]
@tpitale gah, yeah I need to remove examples from that readme, they indeed can confuse people.

You can check out the new [SQL](http://rom-rb.org/guides/adapters/sql/) guide.
