### ISSUE TITLE
Use same timezone as Rails in rom-rails

### ISSUE THREAD

**Issue by nwallace** [rom-rb/rom#285]
Rails configuration includes a timezone setting, but rom-rails does not configure the database layer to use that timezone.

In my app, I'm using rom-sql (for a Postgres DB), so I can workaround this issue by configuring Sequel manually ([docs here](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Timezones.html)), but this seems like the kind of thing it would be good for rom-rails to do automatically

**Comment by cflipse** [comment]
It does.

How are you currently triggering?  Should be _fairly_ easy to throw into the railtie.

**Comment by solnic** [comment]
Not really, rom-rails is not sql-specific so that would have to go to rom-sql gem.

**Comment by cflipse** [comment]
Hrm.  Pointing that out, this actually seems like it's something that should apply to _most_ adapters.  Otherwise, you're mixing data from a *-sql adapter in Eastern, a Mongo adapter in UTC, and a web service in Pacific time ... and that could go Poorly.

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-rails#43
