### ISSUE TITLE
Add ability to register custom coersions

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom#286]
Now that we're moving away from a centralized Transproc function registry, we need someplace to put coersions for domain value objects, so that:

```
BookMapper < ROM::Mapper
  model Book
  attribute :isbn, type: :isbn
end
```

will coerce Book#isbn to an ISBN type value object.

You can do this currently by calling `ROM::Processor::Transproc::Functions.import` but that's gobal, and deeply nested enough that it _screams_ private.  Cleaner, more explicit support in the context of the mappers would be good.

**Comment by solnic** [comment]
Maybe we should use existing mapper dsl:

``` ruby
setup = ROM.setup(:memory)

module MyCoercers
  def self.to_batman(*args)
    Batman.new(*args)
  end
end

setup.mappers do
  coercers MyCoercers
end
```

We could also add support for instantiating structs through:

``` ruby
module Transproc::Coercions
  def self.to_struct(model, *args)
    model.new(*args)
  end
end

class MyMapper < ROM::Mapper
  attribute :location, type: :struct, model: Location
end

mapper = MyMapper.build
mapper.call [{ location: [123, 312] }] # would turn it into a location instance
```

**Comment by c0** [comment]
A lot of the API style is to create a subclass which registers itself. What are your thoughts on:

```ruby
class ISBNCoercer < ROM::Coercer
  register_as :isbn

  def self.call(value)
    value.to_s
  end
end
```

Also, the concept of prefixing with `to_` feels too indirect and requires familiarity with transproc.

**Comment by nepalez** [comment]
@c0 I don't think this should be class, because there is nothing to instantiate

```ruby
module ISBNCoercer
  extend ROM::Coercer

  def self.call(value)
  end
end
```

Here ROM::Coercer could in turn
* `extend Transproc::Registry` (allowing to include external modules and/or their singleton methods),
* define `register_as` method for ROM env

**Comment by AMHOL** [comment]
Please don't add any more `register_as` :(

**Comment by nepalez** [comment]
@AMHOL (1) why? (2) if so, we can simply go with `Transproc::Registry`

**Comment by AMHOL** [comment]
It makes me sad to see state held on a class level like that

**Comment by AMHOL** [comment]
Also, Transproc is an optional dependency, and ROM has an adapter between mappers and Transproc, so I think extending Transproc::Registry in a ROM core component is a no-go

**Comment by c0** [comment]
@AMHOL I'm with you and am all for removing state. I pointed it out because it would be consistent with the rest of the API.

**Comment by nepalez** [comment]
@AMHOL  "Don’t be sad" (c) Magical Deer

Ahh, yes you're right about dependency. Then registering a coerser is no-go.

But I wonder if the whole idea of coercer is coupled to specific mapper. If so, we could mix transproc to mappers and use mappers as local registries except for global one.

**Comment by cflipse** [comment]
No, it's not good to be tied to a specific (single) mapper:

that means, either I have to base-class all my internal mappers, or I have to redo the corecer for every  mapper that happens to use that type.  Since one of the compelling things about value objects is that they can be freely scattered everywhere needed, that could be a _lot_ of mappers.

**Comment by nepalez** [comment]
@cflipse What about base `ROM::Mapper`. We could extend it by `Transproc::Registry` and then add shortcuts `#[]` (aliased as `#t`) to access its singleton methods from every mapper instance, not to mention mapper classes.

**Comment by solnic** [comment]
This would mean we have dependency on Transproc. But maybe that would not be a bad thing. Hmm.

**Comment by nepalez** [comment]
@solnic Well, in `ROM::Mapper` we have that dependency.

We could (as @AMHOL pointed, if I understood it correctly) use other mapper engine, and this make global `ROM` dependency no-go.

**Comment by solnic** [comment]
@nepalez technically speaking ROM uses its default transformer compiler to turn a mapper header into transproc function, but it's not a real dependency, it is decoupled from the implementation pov

**Comment by nepalez** [comment]
Ahh, i see. But this make me curious whether we really expect somebody some time decide to write its own compiler to substitute Transproc? I'd rather expect somebody to write another mapper based on the same transformer :)

**Comment by solnic** [comment]
@nepalez I think it's nice to keep it separate and leave that option, who knows what people could come up with :) But I'm not 100% sure if it's worth the effort.

**Comment by solnic** [comment]
...that's why I'm so eager to see how your abstract_mapper + faceter evolve. If we could establish a solid mapper AST that can be used to produce fast mappers then we could have compilers that turn that AST to *whatever*, be it a transproc function or something else. I also hope that optimizations could be really advanced so that we can keep things very fast.

**Comment by nepalez** [comment]
...I'm trying to faster the process by reading Dragon Book. Seems like this was not a cute idea.

**Comment by cflipse** [comment]
I'm fine with base mapper, if that implied dependency is good with others

**Comment by AMHOL** [comment]
I think the beauty of swappable dependencies, is swappable behaviour, who knows what you could twist and bend ROM to do if you were to replace the transproc dependency, but without the option, we end up with a monkey-patch it and run philosophy that I would avoid at all costs. Middleman adapters FTW IMO.

**Comment by solnic** [comment]
This issue was moved to rom-rb/rom-mapper#8
