### ISSUE TITLE
SQL migration example not working with current rom-sql version

### ISSUE THREAD

**Issue by UrsMetz** [rom-rb/rom#287]
When I created a migration (using rom 0.8.1 and rom-sql 0.5.2) along the lines of http://rom-rb.org/guides/adapters/sql/ I got an SQL exception (the database was a file based sqlite3 database).

I think the reason is that the correct syntax to declare the type of a column is
```ruby
column :name, String
```
instead of
```ruby
column :name, type: String
```
as described on the bottom example page because using the former syntax worked for me :-).

**Comment by solnic** [comment]
Oh, thanks for reporting that - you are right of course, will fix :)
