### ISSUE TITLE
Chain order when composing commands and mappers should not matter

### ISSUE THREAD

**Issue by jaredbeck** [rom-rb/rom#307]
The chain order seems to matter.

    # This works
    ROM.env.command(:users).as(:user).create.call

    # This raises ROM::MapperMissingError
    ROM.env.command(:users).create.as(:user).call

Originally reported as a documentation issue: https://github.com/rom-rb/rom-rb.org/pull/93

**Comment by solnic** [comment]
This should raise a no-method error, we blindly forward method calls to relation which causes `as()` to be available on a command. The only methods that we should forward are relation-view methods, any built-in relation API shouldn't be forwarded.
