### ISSUE TITLE
Problem with ungroup in mappers

### ISSUE THREAD

**Issue by wafcio** [rom-rb/rom#314]
I checked it only with rom-json adapter but it could be general problem.

From relation I receive:
```
[{:name => "test", :entries => [{"title" => 'test'}]}]
```
and with mapper it doesn't work
```
irb(main):001:0> SchedulesMapper.build.call([{:name => "test", :entries => [{"title" => 'test'}]}])
=> [{:entries=>[{"name"=>"test"}], :conference=>"test"}]
```

But it work in this case:
```
irb(main):002:0> SchedulesMapper.build.call([{:name => "test", :entries => [{"title":'test'}]}])
=> [{:title=>"test", :name=>"test"}]
```

**Comment by solnic** [comment]
I think I know what's going on, you have stringified keys but you use symbol keys in your mapper, we should add support for symbolizing keys in lower-level adapter mapping in rom-json, like in rom-yaml, I think

**Comment by wafcio** [comment]
Yes, you are right. I changed attribute name from symbol to string in mapper and it start working.

And yes +1 for symbolizing keys

**Comment by AMHOL** [comment]
This could be fixed by passing `symbolize_names: true` to https://github.com/rom-rb/rom-json/blob/master/lib/rom/json/gateway.rb#L73 and removing https://github.com/rom-rb/rom-json/blob/master/lib/rom/json/dataset.rb#L9-L15 as far as I can tell

**Comment by wafcio** [comment]
You are right. I will extend rom-json by add options like in rom-csv

**Comment by solnic** [comment]
Seems like this is an adapter-specific thingie, so closing it here.
