### ISSUE TITLE
Implement rom-migrator in a separate gem

### ISSUE THREAD

**Issue by nepalez** [rom-rb/rom#315]
WIP at [nepalez/rom-migrator](https://github.com/nepalez/rom-migrator).
Will extract shared features from `rom-sql` and `rom-cassandra`.

**Comment by wafcio** [comment]
:+1:

**Comment by eduardodeoh** [comment]
:+1:

**Comment by muescha** [comment]
FYI: the nepalez repo moved to: https://github.com/rom-rb/rom-migrator

**Comment by solnic** [comment]
FYI we have a schema interface in `Relation` now, you can use it to define all attributes along with types and its meta-data. This can be used as a foundation for inferring migrations, including an auto-migration system that we had in DataMapper.

**Comment by solnic** [comment]
Closing this one since we do have a separate project now, not released yet though.
