### ISSUE TITLE
Improve error when command isn't defined 

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom#324]
```ruby
ROM.use :auto_registration
ROM.setup :memory

class Users < ROM::Relation[:memory]
  register_as :users
end

# when this is removed:
# class CreateUser < ROM::Commands::Create[:memory]
#   relation :users
#   register_as :create
# end

ROM.finalize

rom = ROM.env

create_user = rom.command(:users).create # ==> ElementNotFoundError
```

Produces `ROM::Registry::ElementNotFoundError: :users doesn't exist in ROM::Registry`, but that doesn't describe the precise problem, which is that there is no such *command*. A better error would be something like: 

`ROM::Registry::NoSuchCommandError: There is no :create command defined for :users relation.`

**Comment by kwando** [comment]
+1 xD

**Comment by kelvinst** [comment]
:+1:
