### ISSUE TITLE
Is the logic for Command graph incorrect?

### ISSUE THREAD

**Issue by AMHOL** [rom-rb/rom#325]
Looks like the value for commands with `result :one` is mixed up with `result :many` unless I'm missing something?

https://github.com/rom-rb/rom/blob/master/lib/rom/commands/graph.rb#L67-L78

**Comment by solnic** [comment]
Yes, it looks odd I know. The reason for this is that `result` can be set to either `:one` or `:many` which introduces complexity in the pipeline, that's why we need to wrap results inside arrays so that mappers can handle that.
