### ISSUE TITLE
#many as preferred alias for #to_a

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom#329]
As commands' `#result` accepts `:one` and `:many`, it would be more consistent to use `#many` as the opposite of `#one`/`#one!`. 

Further, "many" is a linguistic opposite to "one", whereas to_a is just a somewhat common Rubyism. 
##

**Comment by solnic** [comment]
I like the name, although I'm not sure if it should be an alias to `to_a` or to `call`.

**Comment by zekefast** [comment]
@solnic by analogy with `#one` and `#one!` it should be alias for `#to_a`, because first two force lazy relations to be resolved, so `#many` should also. IMO

**Comment by solnic** [comment]
Closing this since I don't think it's a good idea after all. `one` and `one!` has special meaning, as they raise errors, `#many` would be different as it would be a simple alias, so it makes no sense.
