### ISSUE TITLE
Pluralize `Configuration#register_relation`

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom#332]
`register_relation` takes an arglist of classes to register, but has a singular name. 

`register_relations` makes more sense, and infers that you can pass many classes.

**Comment by endash** [comment]
This was originally a convenience for internal/spec use... but clearly has broader applicability. I'm divided on a rename since `register_relations` might (1) encourage mistaken use of an array rather than argument list (2) on the flip side, looks weird with just one argument.

**Comment by robinetmiller** [comment]
Why not accept an array as well and convert it? Both make sense to pass in.

**Comment by muescha** [comment]
or add both:
`register_relation` with one argument
`register_relations` with array argument & argument list

**Comment by solnic** [comment]
Closing this one since there was no follow-up for many months. Feel free to re-open if you'd like to work on it.
