### ISSUE TITLE
Ruby Object Mapper - How to change the default order field in a Create command?

### ISSUE THREAD

**Issue by edward6882990** [rom-rb/rom#339]
I am current working on a project that I want to use Ruby Object Mapper with an existing sql database. I am running into a problem when I execute a create command, the returned result seems to sort by table_name.id by default. This is a problem because the existing tables that I am working with has a primary key named other than id, and it causes a unknown column 'id' exception.

I just wonder if there is any possible way to change the default order column?

**Comment by hecrj** [comment]
This is an issue related with `rom-sql` (https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/relation.rb#L39).

The solution is to declare your dataset explicitly in your relation. For example:

```ruby
class MyRelation < ROM::Relation[:sql]
  dataset { order(:my_column) }
end
```

**Comment by edward6882990** [comment]
Thanks!
