### ISSUE TITLE
Table Name Issue

### ISSUE THREAD

**Issue by Reinkaos** [rom-rb/rom#357]
Hey,

This is kind of an odd issue, but I was wanting to use ROM to read from a SilverStripe database into a rails application. 

My problem is basically that SilverStripe names it's tables like Ruby names it's classes, such as 'MyTable'. So I am unable to do something like

``` ruby
class UserRepo < ROM::Repository[:users]
  # find all users with the given attributes
  def query(conditions)
    users.where(conditions)
  end
end
```

as mine would be

``` ruby
class UserRepo < ROM::Repository[:MyTable]
  # find all users with the given attributes
  def query(conditions)
    MyTable.where(conditions)
  end
end
```

Is there a way around this?

Thanks,
Richard

**Comment by kwando** [comment]
Have you tried register relations manually?

```ruby
class UsersRelation < ROM::Relation[:sql]
  register_as(:users)
  dataset(:UsersTable)
end
```

**Comment by Reinkaos** [comment]
Oh na I didn't see that you could do that :). I will give that a go, thanks!

**Comment by solnic** [comment]
Is it still a problem?

**Comment by solnic** [comment]
Closing this since I'm pretty sure setting `register_as` solves this problem
