### ISSUE TITLE
Inherited, duped, or cloned repositories & relations ignore schema attribute definitions

### ISSUE THREAD

**Issue by ginjo** [rom-rb/rom#359]
I'm not sure if this is an actual issue, or if it's just the way I'm using ROM.

I have a relation with schema and some custom defined dry-types. I have a repository that uses that relation. All is well when finalized into a rom container - the custom types convert raw data into something the db can ingest.

If I subclass (or clone, or dup) the relation class and the repository class, then finalize these new objects in a different rom configuration and container, the schema appears to be ignored when using commands from the subclassed repository.

So this works.

```ruby
class UsersRelation < ROM::Relation[:sql]
  register_as :users

  schema do
    attribute :id, Types::Integer
    attribute :info, Types::ToYaml
  end
end

class UsersRepo < ROM::Repository[:users]
  commands :create, :update, :delete
end

RomConfiguration = ROM::Configuration.new(:sql, 'postgres://localhost/my_db')
RomConfiguration.register_relation UsersRelation
RomContainer = ROM.container(RomConfiguration)

Users = UsersRepo.new(RomContainer)
Users.create(info: {this:'hash', becomes:'serialized', as:'yaml'})
```

But this Doesn't work - the schema types are ignored.

```ruby
class UsersRelationSubclass < UsersRelation
# or UsersRelationSubclass = UsersRelation.clone
end

class UsersRepoSubclass < UsersRepo
# or UsersRepoSubclass = UsersRepo.clone
end

RomConfigurationTwo = ROM::Configuration.new(:sql, 'postgres://localhost/my_db')
RomConfigurationTwo.register_relation UsersRelationSubclass
RomContainerTwo = ROM.container(RomConfigurationTwo)

UsersTwo = UsersRepoSubclass.new(RomContainerTwo)
UsersTwo.create(info: {this:'hash', remains:'unaltered'})

# => raises postgres column-not-found error, as it's trying to push the raw hash into the db.
```

Subclassing simple ROM objects would be helpful for my projects, but is this the wrong way to go about it? Or is this perfectly legit - and something that can be fixed or worked around?

**Comment by ginjo** [comment]
Edit: I realize that subclassing a relation class will lose the schema definition. Fair enough. But cloning it does not lose the schema.

**Comment by ginjo** [comment]
Hmmm... well I am not able to reproduce the issue with the above example. So there must be something about my project that is interfering with functionality of schema types.

One thing I have noticed is that ROM containers are not isolated: Two separate ROM containers in my project are showing relations from each other. When they are set up, they don't reference each other at all, yet somehow the relations are bleeding into each other. Maybe this is related to the other issue I'm having?

**Comment by solnic** [comment]
I'll investigate that prior 2.0.1 release. Optimistic scenario is that it turns out to be something simple to fix and it'll go into 2.0.1. If it's something that needs more changes, we may have to wait until 2.1.0 or even 3.0.0 (in case it'd require a breaking change). Thanks for feedback.

**Comment by ginjo** [comment]
@solnic, thanks for the consideration. I'm going to let this go and close it out. I'm almost certain it's something on my side breaking the schema or dry-types. I tried several other fresh examples of increasing complexity and still couldn't reproduce the issue - which is good! :smile:  I think I was getting tripped up by the automatic relation inference in rom-sql https://github.com/rom-rb/rom-sql/issues/96  at one point and ultimately went looking down the wrong road.

**Comment by solnic** [comment]
That's very likely, that's why I reported this issue about turning inference off by default, so that it's a conscious decision rather than a surprise :)
