### ISSUE TITLE
ROM::Relation::Name#to_s outputs a symbol instead of a string

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [rom-rb/rom#361]
It's very hard for me to write an example (there is a lot of boilerplate), but in general, something like the following (I have a table named `logs` with a repository named `LogRepo`)

```
log_repo.relations.logs.name.to_s # => :logs
```

The change should be as simple as changing https://github.com/rom-rb/rom/blob/f914d5bd4a68a9394740c808f52f30ac322d3f4c/lib/rom/relation/name.rb#L68 to `relation.to_s`

**Comment by solnic** [comment]
ooops, nice catch. I'll fix it quickly :) thanks for reporting <3

**Comment by Fire-Dragon-DoL** [comment]
No problem, sorry for not submitting a PR @solnic , I was really in hurry

**Comment by solnic** [comment]
@Fire-Dragon-DoL no worries :) it's been fixed in 2.0.2 and released today
