### ISSUE TITLE
Auto-Registration and custom namespacing strategies

### ISSUE THREAD

**Issue by pnomolos** [rom-rb/rom#380]
I have a case where my base namespace is all caps ("VO", in this case).  

- `true` namespace strategy doesn't work, because it's looking for "Vo" instead of "VO"
- custom namespace doesn't work because I want to have things like "VO::Relations" and "VO::Commands"

Has any consideration been given to either allowing custom strategies to be registered or to add a `base_namespace:` option that would allow you to specify the base to work from (to which "Relations", "Commands", etc, would be appended)?

**Comment by Kukunin** [comment]
oh. it affected me as well. Currently I don't have a better solution than put `Vo` namespace for you, 
but in case you want to spend more time with this issue, you can take a look into implementation.

https://github.com/rom-rb/rom/blob/master/lib/rom/setup/auto_registration.rb#L50

Main problem that it's looking for all files via glob, and tries to guess their namespace, which is inaccurate

**Comment by solnic** [comment]
the inflector can't possibly know that `vo` should become `VO` so you need to configure it properly. I don't know if inflecto supports this to be honest, but if you're using ActiveSupport::Inflector then it can be done there.

**Comment by pnomolos** [comment]
Yeah, I realized that the inflector has no way of knowing.  I'm not using AS so I'll see if Inflecto can be configured to do that.  Forgot about doing it that way.  This can be closed now, unless you want to explore the possibility of registering a custom namespacing strategies.

**Comment by solnic** [comment]
What would that custom namespacing strategy do?

**Comment by pnomolos** [comment]
The same thing that say `AutoRegistrationStrategies::CustomNamespace` does, but the logic can be defined to whatever you want if you have some weird requirements.  I don't know if add the ability to do that is worth the added complexity, though.

Basically `load_entities(entity)` would call `MyCustomStrategy.call(file: file, directory: directory, entity: component_dirs.fetch(entity)` if you had requested that strategy be used to resolve things.

**Comment by flash-gordon** [comment]
Probably having an alias for `VO`, like `Vo = VO`, is also an option.

**Comment by pnomolos** [comment]
@flash-gordon Yep that's true.  I just ran into the "issue" and brought it up in case it may be something that could be improved.  Again, not sure if the ability to do this is worth the trade-off.  It's unlikely you'll be needing to pull in a legacy file structure to ROM ;)

**Comment by solnic** [comment]
It'd be good to update docs with information about inflections. I think we don't need extra strategies or ability to define your own. If your setup is not typical you can always just go through your dirs and register components manually via `Configuration#register_*` methods.

**Comment by solnic** [comment]
@pnomolos looks like inflecto doesn't support registering custom acronyms :( I also looked into hanami inflector, but same problem there. So you either need to use AS::Inflector or just register your components manually
