### ISSUE TITLE
Publish release notes for services like sibbell.com?

### ISSUE THREAD

**Issue by zavan** [rom-rb/rom#385]
[Sibbel](https://sibbell.com/) is a service that notifies devs about package updates:

![image](https://cloud.githubusercontent.com/assets/1722965/23525111/11c5bb78-ff6c-11e6-92e0-205fe89653d4.png)

It shows release notes in the email and website:

![image](https://cloud.githubusercontent.com/assets/1722965/23525205/6541a172-ff6c-11e6-8961-0e3fb9a41d18.png)

But not when they're not filled :(

![image](https://cloud.githubusercontent.com/assets/1722965/23525223/79e3faee-ff6c-11e6-9fbf-b9334d94f244.png)

So it would be nice if you could include release notes with the tags.

(I'm not affiliated to sibbel in any way)

**Comment by solnic** [comment]
I don't know how this service works, but we do keep an up-to-date CHANGELOG *all the time*. So I'm not sure what we're supposed to do to make it work with sibbel. I like the idea so I'd appreciate any help with integrating.

**Comment by zavan** [comment]
@solnic Sibbel and other services read it from GitHub's release notes. 

It's basically step 6 of this guide: https://help.github.com/articles/creating-releases/

![Release](https://help.github.com/assets/images/help/releases/releases_description.png)

Since you already keep a CHANGELOG, you can simply copy the entry from the CHANGELOG to the GitHub release when creating the release tag (although it may not be so simple if your release process is automated).

**Comment by solnic** [comment]
OK I'll start including release notes in tag commit messages, this should do the trick
