### ISSUE TITLE
Extract rom/changeset gem from rom/repository

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#399]
Everything related to `Changeset` can be moved from `rom/repository` to `rom/changeset` which will become a separate gem

**Comment by kwngo** [comment]
Hey! New to contributing to `rom` but I've been using gem for a while. Would love to help with this, and sounds like a good first PR?

**Comment by solnic** [comment]
@kwando hey, thank you :) it's definitely a good candidate, as it's mostly moving things from one place to another.

**Comment by solnic** [comment]
@kwngo hey, thank you :) it's definitely a good candidate, as it's mostly moving things from one place to another.

**Comment by kwngo** [comment]
Awesome! I'll take a look at the structure of the other directories and get started..

**Comment by solnic** [comment]
Cool, let me know if you have any questions.

**Comment by solnic** [comment]
@kwngo no pressure whatsoever but did you make any progress? We're trying to move fast and hit 4.0 beta in a couple weeks so if this doesn't feel like a good task for you after all, please let me know.

**Comment by GustavoCaso** [comment]
Can we close this one? @solnic

**Comment by solnic** [comment]
Yes, closing now via #426
