### ISSUE TITLE
Extract registering arbitrary mappers from rom/mapper to rom/core

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#402]
So in #401 we moved everything related to mappers to rom/mapper, but there's one caveat there - we have a way of registering arbitrary mapper objects via `Mapper::ConfigurationDSL#register`. So the trick is that the code that is specific to rom/mapper is only `mappers { define(...) { ... } }` which exposes mapper DSL, but `mappers { register(..) { ... } }` is just a way of registering anything as a mapper, and this should be part of core.

**Comment by GustavoCaso** [comment]
I can help with this one

**Comment by solnic** [comment]
Closing this as it isn't easily solvable at this point. I'll revisit it after 4.0.
