### ISSUE TITLE
Specify aliases for classes to use in repository struct_namespace

### ISSUE THREAD

**Issue by timriley** [rom-rb/rom#413]
struct_namespace allows users to control and customise their struct code, but so far repos don't allow  any control over _which_ struct class is used for the returned results. Users may not want all of their struct behaviour kept in a small number of classes directly matching the relation names.

I mentioned this to @solnic and he suggested that something like this should exist in 4.0:

> `users.alias(:admins).select(:id, :email)` would auto-map to `Entities::Admin` structs

Ping @flash-gordon – does that seem doable to you?

**Comment by flash-gordon** [comment]
This sounds 💯 reasonable, I can confirm there are no obstacles to support this as described

**Comment by solnic** [comment]
There's one more thing I should mention - a lot of people asked for a way to mimic polymorphic assocs from AR because they are working with legacy schemas. So, in rom-4 something like this should be possible:

``` ruby
class Admins < Users
  dataset { where(type: 'Admin') }
end
```

Now, because this would be registered under `:admins` then `Entities::Admin` should be automatically inferred, and you can do `Admin < User` to share common behavior like in STI in AR.

**Comment by flash-gordon** [comment]
@solnic I'm not sure if inheritance in relations is going to work well

**Comment by solnic** [comment]
@flash-gordon I'm aware of this, and I'd like to at least give it a shot (I know it won't work OOTB right now). Worst case people will have to define separate relations and configure schemas.

**Comment by solnic** [comment]
@flash-gordon I made inheritance work, but without schema inheritance as it's tricky as hell due to the fact `schema` is both get or set schema proc. Not sure how to solve this yet.

**Comment by flash-gordon** [comment]
@solnic mb copying `@schema_proc` is enough

**Comment by solnic** [comment]
@flash-gordon not when you want to set a different relation alias :)

**Comment by flash-gordon** [comment]
ahh, right, actually I tried to "fix" that inheritance thing but gave up quickly

**Comment by solnic** [comment]
if we separate schema reader from setter things should become simpler, we use instance schemas at runtime anyway so class-level schemas can be accessed using a different method
