### ISSUE TITLE
Deprecate and remove `Container#{relation,command}`

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#424]
Both methods go back to the early days when we didn't have auto-mapping and auto-commands. Now that relations can infer both mappers and commands it makes very little sense to keep these two methods in rom 4.0.

`Container#relation` was added before 1.0 in order to provide a convenient access to a relation that's automatically mapped by a mapper with a corresponding relation name, but now since we have auto-mapping barely anyone will use custom default mappers.

`Container#command` was added before 1.0 and then extended a lot in 2.0 so that it can provide a way of accessing a registered command or providing a DSL for configuring a complex command graph. Similarly to `Container#relation` it would auto-map through a custom registered mapper with a matching relation name. All 3 use cases are no longer needed. Command graph builder could be considered as a useful feature, however for `create` commands we have auto-commands, and for `update` and `delete` commands, defining a graph through DSL is so complex (despite our greatest efforts) that it doesn't feel good to keep this feature. I'm much more inclined to experiment with extending changesets to support complex update/delete scenarios than to re-iterate on command graph builder DSL.

This is a proposal but based on a strong opinion ;) Please let me know if you disagree.

**Comment by cflipse** [comment]
Does this leave, eg `container.relations[:users]` ?

**Comment by solnic** [comment]
@cflipse yes

**Comment by flash-gordon** [comment]
I completely forgot this works this way. And I agree now it looks alien to the features we have. This _probably_ will break some code of people who still use ROM from the pre-1 era but it's unlikely they prefer these methods over auto-*s. We just should offer them a _before_/_after_ upgrade plan

**Comment by solnic** [comment]
> We just should offer them a before/after upgrade plan

I'll write upgrade notes in the wiki, and this is as simple as:

``` ruby
# before
rom.relation(:users)

# after
rom.relations[:users].map_with(:users)
```

and so on, and if somebody is using custom mappers for basic stuff, then it's about removing mappers altogether, so I'm sure folks will appreciate this ;)

**Comment by solnic** [comment]
This is done in master
