### ISSUE TITLE
Raise a meaningful error if relation name is one of the reserved names

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#434]
For now we know that `relations` can't be used as a name of a relation. Would be good to look into code and figure out if there are any other names that could break things.

**Comment by GustavoCaso** [comment]
@solnic I'm happy to help with this one

**Comment by solnic** [comment]
@GustavoCaso cool. Let's start with `relations` then. We can then add more reserved names easily whenever we discover them.
