### ISSUE TITLE
Date based restriction doesn't work with command macro

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#435]
_From @daniels on June 19, 2017 12:27_

When trying to use a time/date based restriction from a commands macro, the DateTime or Time object passed in as a parameter is converted to an Array and then splatted against the filter method, causing an ArgumentError.

The SQL-relation `:requests` has a `:created_at` column, and `Requests#expired` is defined:
```ruby
def expired(expiration_time=default_expiration_time)
  where{ created_at < expiration_time }
end
```

The commands macro is used like this:
```ruby
r = Class.new(ROM::Repository[:requests])  do
  commands delete: [:by_pk, :expired]
end.new(rom) 
```

And calling the generated method:
```ruby
r.delete_expired(Time.now)
#=> ArgumentError: wrong number of arguments (given 10, expected 0..1)
```

_Copied from original issue: rom-rb/rom-repository#93_

**Comment by solnic** [comment]
Thanks for reporting this. I'll fix it in 1.x and port it to rom-rb/rom master.

**Comment by GustavoCaso** [comment]
I would like to help with this one

**Comment by solnic** [comment]
@GustavoCaso it's all yours (:
