### ISSUE TITLE
Add migration layer/library

### ISSUE THREAD

**Issue by postmodern** [rom-rb/rom#44]
There should be some sort of either explicit and/or automatic migration support. Ideally with the following features:

1. Ability to easily define migrations via a DSL syntax.
  * Syntax should be easy enough to define one-off migrations in `irb` or define complex migrations for `db/migrations/`.
2. Ability to convert ROM Schema objects into adapter specific schema objects.
  * Example of this would be mapping ROM attribute types to adapter specific types, and defining which attributes need keys and/or indexes.
3. Ability to query and load schema information from the adapter.
  * This would be useful for diffing the ROM schema against the actual current schema and generating a set of auto-migrations, which would either be executed or dumped out into `db/migrations/`.

**Comment by gotar** [comment]
Do we still need this ticket, we have basic migrations?

**Comment by solnic** [comment]
Yes we can close this one

**Comment by solnic** [comment]
Yes we can close this one
