### ISSUE TITLE
Remove `#aggregate` method from repo

### ISSUE THREAD

**Issue by timriley** [rom-rb/rom#453]
This does nothing more than forward arguments to `#combine` on the root relation. Keeping this method here makes repos more confusing (users need to understand how aggregate works, and its special connection to the root relation) and also confuses the fact that a repo should be able to work with more than one relation.

**Comment by timriley** [comment]
@solnic reckon this is worth getting done before 4.0.0?

**Comment by solnic** [comment]
@timriley not really, feels too late. I'll remove it in rom-repo 3.0 and for now just remove it from docs and deprecate in rom-repo 2.1

**Comment by flash-gordon** [comment]
@solnic for now, we could add an alias `alias_method :combine, :aggregate`
