### ISSUE TITLE
API documentation for Repository still uses changeset directly on repo

### ISSUE THREAD

**Issue by daniels** [rom-rb/rom#454]
I just tried out 4.0.0.rc1 on my existing code, and my use of `repo.changeset` caused a `NoMethodError`. When trying to find out why, I noticed that the current API documentation (i.e. in the source) for `Rom::Repository` and `Rom::Repository::Root` both still contain examples where `changset` is called directly on a repo.

As I just stumbled over this and have little knowledge of the changes, I'm still not sure if it's the documentation or the implementation that is wrong.

(I guess I should reference the changeset on the specific relation now: `repo.my_relation.changeset` ?)

**Comment by solnic** [comment]
Yes, starting with rom 4.0 we have `Relation#changeset` and `Repository#changeset` is gone. I'll be updating docs before final is released.
