### ISSUE TITLE
Warnings during startup

### ISSUE THREAD

**Issue by graywolf** [rom-rb/rom#457]
I'm getting warnings

    /home/wolf/dennas/dia/vendor/bundle/ruby/2.4.0/gems/rom-3.3.2/lib/rom/types.rb:11: warning: already initialized constant #<Module:0x000055b6e6f082d0>::JSON
    /home/wolf/dennas/dia/vendor/bundle/ruby/2.4.0/gems/rom-3.3.2/lib/rom/types.rb:11: warning: previous definition of JSON was here
    /home/wolf/dennas/dia/vendor/bundle/ruby/2.4.0/gems/rom-3.3.2/lib/rom/types.rb:12: warning: already initialized constant #<Module:0x000055b6e6f082d0>::JSONHash
    /home/wolf/dennas/dia/vendor/bundle/ruby/2.4.0/gems/rom-3.3.2/lib/rom/types.rb:12: warning: previous definition of JSONHash was here
    /home/wolf/dennas/dia/vendor/bundle/ruby/2.4.0/gems/rom-3.3.2/lib/rom/types.rb:13: warning: already initialized constant #<Module:0x000055b6e6f082d0>::HashJSON
    /home/wolf/dennas/dia/vendor/bundle/ruby/2.4.0/gems/rom-3.3.2/lib/rom/types.rb:13: warning: previous definition of HashJSON was here

during `bundle exec hanami server`. Since it's in the `gems/rom`, I'm reporting it here (hope it's correct).

Ruby version: `ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]`

**Comment by AlexanderMint** [comment]
Same problem
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by flash-gordon** [comment]
Fixing this requires applying https://github.com/rom-rb/rom/commit/cb838f49d5d045e2e8ab0bbab48ef80c3b4b1108 to the `release-3.0` branch, can't do it right now. If anyone wants to help with this it would be great

**Comment by graywolf** [comment]
Will do later today.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Nikita ShilnikovSent: Tuesday, October 17, 2017 10:32To: rom-rb/romReply To: rom-rb/romCc: W.; AuthorSubject: Re: [rom-rb/rom] Warnings during startup (#457)Fixing this requires applying cb838f4 to the release-3.0 branch, can't do it right now. If anyone wants to help with this it would be great

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rom-rb/rom","title":"rom-rb/rom","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/rom-rb/rom"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flash-gordon in #457: Fixing this requires applying https://github.com/rom-rb/rom/commit/cb838f49d5d045e2e8ab0bbab48ef80c3b4b1108 to the `release-3.0` branch, can't do it right now. If anyone wants to help with this it would be great"}],"action":{"name":"View Issue","url":"https://github.com/rom-rb/rom/issues/457#issuecomment-337158227"}}}

**Comment by flash-gordon** [comment]
@graywolf @AlexanderMint 3.3.3 with the fix is on rubygems 🎉

**Comment by graywolf** [comment]
@flash-gordon thank you for the quick release :) Can confirm the warnings are not printed anymore.
