### ISSUE TITLE
Write a nice README

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#46]
The README should explain the philosophy behind the project, main differences between ROM and other typical ruby ORMs and show how to quickly get started with ROM showing some basic examples. It should also have a nice CREDITS section mentioning DM2, Axiom and people behind all the initial efforts.

/cc @elskwid HELP NEEDED HERE :)

**Comment by solnic** [comment]
@elskwid now we gotta do something with this one ha-ha ;)

**Comment by cored** [comment]
@solnic is there some progress on this or something from where I can extract info. I want to learn more about the philosophy that you mention in here.

**Comment by solnic** [comment]
Any idea what should be presented in Synopsis section? Right now it's rom-sql example which I don't like. Something in-memory should be enough. Question is: what should it be? /cc @aflatter @elskwid @kwando @splattael

**Comment by cored** [comment]
Maybe I'm misunderstanding the idea but you guys can correct me. Aren't we
aiming to have something like entity framework from Microsoft?

**Comment by solnic** [comment]
I'm not familiar with entity framework from MS

**Comment by cored** [comment]
They have an example building an app with it; so maybe the README could
make an example like this. Like with the in-memory adapter but showing the
modeling side of the entire process?

On 13 January 2015 at 11:29, Piotr Solnica <notifications@github.com> wrote:

> I'm not familiar with entity framework from MS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rom-rb/rom/issues/46#issuecomment-69772708>.
>



-- 
Rafael George

**Comment by solnic** [comment]
I don't think README is a good place for such a huge piece of information, esp that you can use ROM in all sorts of ways.

**Comment by solnic** [comment]
Closing as the README is now nice-enough ;)
