### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by VitaliyKovtun** [rom-rb/rom#466]
Hey. Is there any way to make a callback, if update or create actions are performed? Like to do some method, when another method is executed. Can I use it this way? Thanks.

**Comment by flash-gordon** [comment]
hey, @VitaliyKovtun pls post questions to https://github.com/rom-rb/rom/issues/466

As for callbacks we discourage from using them for business logic, if you have a different case for them pls post it to discourse so we can discuss it there
