### ISSUE TITLE
Can't use timestamps plugin from inside a repo

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#467]
_From @alexandru-calinoiu on April 23, 2017 15:36_

My repo look like 

```
    class Entries < IngestService::Repository[:entries]
      relations :ingest_steps
      commands :create, use: :timestamps
   end
```

I expect that calling `Entries.new.create(args)` will add timestamps to my entry, but that is not the case.

The `Timestamp` plugin get's applied at runtime when I call create, only then `ClassInterface` is extended adding `timestamps` method that can be used to configure the colmuns. Without calling `timestamps` the `InstanceMethods` will never be included and thus timestamps never added.

Unfortunately my understanding of the plugins is very limited, they look like being targeted mostly to commands, will love some pointers for the right direction.

_Copied from original issue: rom-rb/rom-sql#189_

**Comment by solnic** [comment]
_From @alexandru-calinoiu on April 23, 2017 15:37_

One easy way to solve it is for the timestamp_column to have default values, but is not complete as one won't be able to configure them from a repo.

**Comment by solnic** [comment]
Ah, right. I'm sorry I forgot we didn't make `timestamps` plugin work with repos yet. This will be addressed in rom 4.0 as we need to improve plugin architecture first.

**Comment by solnic** [comment]
In order to make this work, we need to enable passing options for command plugins [here](https://github.com/rom-rb/rom/blob/master/core/lib/rom/commands/class_interface.rb#L112-L114) and then refactor [timestamp](https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/plugin/timestamps.rb) plugin, so that `Timestamp` is a `Module` subclass, and accepts options. Then based on these options we can automatically configure a command. I would also say that this plugin should be moved to core, as it is not sql-specific.

**Comment by GustavoCaso** [comment]
@solnic I would love to help with this one

**Comment by solnic** [comment]
Done via https://github.com/rom-rb/rom/commit/962bb273931a7b224bfb0c4eb52e940f76af7e40
