### ISSUE TITLE
Curious about inheriting from Module

### ISSUE THREAD

**Issue by sumancc** [rom-rb/rom#471]
https://github.com/rom-rb/rom/blob/07bd1da9a826d757a7c2b3f92754a77d48db15ad/core/lib/rom/plugins/command/timestamps.rb#L23

I stumbled across this line via a colleague today. What is the reason behind inheriting from `Module`?

**Comment by solnic** [comment]
You can read about it [here](http://dejimata.com/2017/5/20/the-ruby-module-builder-pattern). Also, please read [CONTRIBUTING.md](https://github.com/rom-rb/rom/blob/master/CONTRIBUTING.md), we don't use issues on github for random questions.
