### ISSUE TITLE
Links are broken in documentation footers.

### ISSUE THREAD

**Issue by alex-oleshkevich** [rom-rb/rom#565]
These links have `%%7Bversion%7D` instead of version number.
Clicking on it leads to 404.

Example:
https://rom-rb.org/5.0/learn/core/schemas/

and all other pages too.

![image](https://user-images.githubusercontent.com/635848/65837163-f7e31080-e2fc-11e9-8020-74533477dcd4.png)

**Comment by solnic** [comment]
Thanks for reporting this, I've fixed it via https://github.com/rom-rb/rom-rb.org/commit/890948a1aa72c55e8dda52ff96eeb2cd6ea8d26f

ps. bugs related to the website should be reported in rom-rb/rom-rb.org repo 😄
