### ISSUE TITLE
Missing require in repository

### ISSUE THREAD

**Issue by qortex** [rom-rb/rom#598]
**Describe the bug**

Somewhere in my code, this fails:
```
require 'rom/repository'
```

And this fixes:
```
require 'rom/plugins'
require 'rom/repository'
```

It didn't appear in other places because I must have required `rom` in those places. I guess it's not intended though, and that the `require 'rom/plugins` should be included in the `rom/repository` file?

**Comment by solnic** [comment]
This is indeed a missing require statement
