### ISSUE TITLE
Using Repository#transaction with non-default gateways

### ISSUE THREAD

**Issue by MasanoriOnishi** [rom-rb/rom#620]
## Describe the bug

I use the code following this, to realize multiple database connection.
```
ROM.container(
  default: [:sql, 'mysql2://localhost/common_tasks'], # gateway 1
  sub: [:sql, 'mysql2://localhost/each_tasks']           # gateway 2
) do |config|
    # setup code goes here...
end
```
And I want to use transaction for both gateway.
However, due to the following code, I can use transaction only for `default` gateway.
https://github.com/rom-rb/rom/blob/master/lib/rom/repository.rb#L151

## Expected behavior

We can use transaction for each gateway in the use of multiple database connection.

https://github.com/rom-rb/rom/blob/master/lib/rom/repository.rb#L151

I think I want to fix the code in the following way.

- before
```
    def transaction(*args, &block)
      container.gateways[:default].transaction(*args, &block)
    end
```

- after
```
    def transaction(*args, &block)
      container.gateways[self.root.gateway].transaction(*args, &block)
    end
```

## My environment

- Affects my production application: **YES**
- Ruby version: 2.7.2
- OS: MacOS Catalina 10.15.7

**Comment by flash-gordon** [comment]
This is not a bug. The `Repository` class doesn't have access to `gateway`. I think we could use keywords for providing a gateway and change its default value in `Repository::Root`. I'll send a PR today but it'll be a breaking change so 6.0 only. In the meantime, you can define your own method for using transactions, nothing really depends on the default implementation.

**Comment by v-kolesnikov** [comment]
In the same case I just redefined `#transaction` method in my root repository.
