### ISSUE TITLE
Associated entities are not mapped to their entity-classes in case of alias

### ISSUE THREAD

**Issue by wuarmin** [rom-rb/rom#673]
## Describe the bug

I have a rom-sql project and use auto-struct with custom entity classes. That works perfectly. My repos return instances and their association-instances of my custom entity classes. However, as soon as I use the `as` option in an association definition, the association result is no longer mapped to the corresponding entity.

## To Reproduce

```ruby 
module Orm
  module Relations
    class Posts < ROM::Relation[:sql]
      schema(:posts, infer: true) do
        associations do
          belongs_to :user, as: :create_user, foreign_key: :created_by
          belongs_to :user, as: :update_user, foreign_key: :updated_by
        end
      end
    end
  end
end
```

```ruby
post = posts.combine(:create_user)
        .by_pk(1).one

expect(post).to be_a(Entities::Post) # success
expect(post.create_user).to be_a(Entities::User) # fails it is a instance of Entities::CreateUser
```

## Expected behavior

```ruby
expect(post.create_user).to be_a(Entities::User)
```

## My environment

```ruby
# ruby 2.7 Ubuntu
gem "rom", "~> 5.2"
gem "rom-sql", "~> 3.5"
```

**Comment by wuarmin** [comment]
That's a duplicat of #581. Sorry. But a solution would be great

**Comment by solnic** [comment]
Thanks for reporting this, closing as a duplicate. It's scheduled for 6.0.

**Comment by wuarmin** [comment]
Looking forward to 6.0 👍
