### ISSUE TITLE
Add Neo4j adapter

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#69]

**Comment by maetl** [comment]
See: https://github.com/maetl/rom-neo4j

This raises a few questions about how best to integrate the concept of traversals over a sub-graph with the existing concepts of datasets and relations.

**Comment by solnic** [comment]
We moved maetl's repo to the rom-rb org: https://github.com/rom-rb/rom-neo4j

**Comment by maetl** [comment]
:smile_cat:
