### ISSUE TITLE
Provide help for adapter development

### ISSUE THREAD

**Issue by elskwid** [rom-rb/rom#86]
Yesterday I spent way too much time, mostly my fault, getting `rom-csv` started. @solnic and I think that `rom` can help in a few ways. In what ways can it help?

## linting
We are already thinking about a linter in #81. This would give some good feedback on whether or not an adapter meets the basic requirements of `rom`. That conversation will happen over there.

## common functionality
ROM already provides a [memory adapter](https://github.com/rom-rb/rom/blob/master/lib/rom/adapter/memory.rb) that does some nifty stuff. The `rom-demo` [subclasses the `Dataset`](https://github.com/solnic/rom-demo/blob/master/lib/github_adapter.rb#L27-L38) out of the memory adapter to provide some ease of use. 

Should we ship a few basic adapters that take into account the common use cases? By this I mean, when we find a common way of dealing with a problem it might be good to have it in `ROM:Adapter:X`.

Minitest does this for [reporters](https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L402-L635) so you can easily build new reporters that conform to the requirements of the underlying lib.

Here's some ideas off the top of my head:

* Provide a nice pattern for the proxy/delegation chain in adapters. We use `Charlatan` for this now and it's super powerful but perhaps we can solidify how it should be used.
* In memory adapter – anything else we need to add? (we already have this)
* Enumerable adapter – any adapters that happen to include enumerable may provide some extra pain (this is what bit me with `rom-csv`). One idea is that we have a module or superclass that ensures things are wired up the way they should be.
* File adapters – we've already written two simple adapters that rely on data in files: `rom-yaml` and `rom-csv`. The YAML adapter assumes you'll have all your 'relations` in a single file and CSV has to assume that one file is one relation is one adapter. What about a file adapter that knows how to deal with one or more files and provides an interface to make this much easier? Config option, mapping file names to relations, etc.
* Write more adapters! It is only through the creation of more of that these use cases will emerge. 

Any thoughts?

**Comment by solnic** [comment]
I believe the most important thing from this list is ironing out a pattern for proxy (some data-pipe kind of a thing) and a common dataset superclass for adapters that happen to use enumerable datasets. This should make it much easier to write a new adapter that provides a dataset out-of-the-box. I also don't think that Charlatan is a good solution here, I've got a feeling we should have something more dedicated.

The rest feels more like nice-to-haves.

**Comment by solnic** [comment]
OK so now we have something like this:

``` ruby
class AdapterDataset
  include ArrayDataset

  def self.row_proc
    -> row { row.to_h }
  end
end

# constructor accepts a data object
ds = AdapterDataset.new(some_hash_serializable_object_array)

ds.to_a # will run `to_h` on all entries

ds.find_all { |row| # here we also get entries processed via row_proc }

# all enumerable and array methods are available too
```

This means if you're building an adapter that wraps some array-like object then this module is very handy. If the data object is not an array-like object but it implements enumerable interface then you can do `include EnumerableDataset`.

**Comment by solnic** [comment]
Do you think all adapters will always need a "connection" concept? So far it is true but maybe that's not a good assumption? Right now abstract adapter provides `:connection` reader and calls `setup_connection` hook in the constructor (which is a no-op by default, so it's not required to implement it). Nice thing about it is that a specialized adapter no longer has to override constructor to setup its connection but what if there's much logic required to instantiate an adapter?

**Comment by solnic** [comment]
FYI I renamed `setup_connection` => `setup` which sounds more generic

**Comment by solnic** [comment]
With 16+ adapters built I think we did a good job :) Still more to do but I think we can close this issue. Re-open in case you disagree.
