### ISSUE TITLE
Where does the rom variable in controller come from ?

### ISSUE THREAD

**Issue by chenge** [rom-rb/rom#88]
Could I ask here?

**Comment by solnic** [comment]
It's a method defined by [rom-rails](https://github.com/rom-rb/rom-rails) railtie. It defines it on `ApplicationController`

**Comment by chenge** [comment]
QUESTION is, remove the require, why the test passed?

module RomTodoApp
  class Application < Rails::Application
    #require 'rom-rails'

**Comment by solnic** [comment]
probably because bundler requires it anyway

**Comment by solnic** [comment]
I'm going to close this issue. If you see any weird behavior and think there's a bug please report it under [rom-rails](https://github.com/rom-rb/rom-rails/issues) project.
