### ISSUE TITLE
Adapter shouldn't equalize on connection

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#94]
It is currently not guaranteed that `connection` in an adapter is not mutable, furthermore `connection` isn't really a required interface (it was put into abstract adapter as all existing adapters are setting a connection but it's probably a good idea to remove it and let individual adapters handle their connection-related concerns themselves). Because of this we shouldn't equalize using `connection`, this is very important as we rely on adapter equality when ROM runs its setup process.

To improve this it should be changed to equalize on `:uri` and `:options` because they always exist and we should freeze them too. This also makes me think abstract adapter should provide the constructor and we should have a hook that's called there so that specialized adapters can set the rest up without the need to override constructor.

Thoughts?

refs #86

**Comment by aflatter** [comment]
I'm for removing `connection` from the abstract adapter. Additionally, I'm still of the opinion that in case of this bug object identity would have been the better default, because that's what we expect. Equality on `uri` and `options` might shadow similar issues, e.g. hidden state in the adapter where ROM assume's there is none.

+1 for not having to override `#initialize`.

**Comment by solnic** [comment]
@aflatter just spent some time thinking about this and you're right, this would be a big assumption and even if we freeze them it might cause issues, so we would have to dup them before freezing, also we would have to deep-freeze them as we're talking about an option *hash* here, so, more complexity.

I'll just remove equalizer (bye bye nice inspect ;))

**Comment by aflatter** [comment]
You could use equalizer on `object_id` I guess ;-)

**Comment by solnic** [comment]
@aflatter that won't work as equalizer defines [hash](https://github.com/dkubb/equalizer/blob/master/lib/equalizer.rb#L65-L70) method which is used internally in `Hash#[]` IIRC

**Comment by aflatter** [comment]
So we're not removing `connection`?

**Comment by solnic** [comment]
I'm not sure yet :) So far all adapters need to set up some kind of a "connection".

**Comment by solnic** [comment]
@aflatter I followed up with connection-related discussion in #86
